### ISSUE TITLE
Namenleertool halveert personen

### ISSUE THREAD

**Issue by asdfCYBER** [csrdelft/csrdelft.nl#1035]
Met 'onderkant verbergen' aan worden personen gehalveerd. Lijkt me slecht voor de gezondheid, kan deze regel worden aangepast of hoort het zo?
https://github.com/csrdelft/csrdelft.nl/blob/0631cb2bd40eef170fb5621b6497d263b73ed765/assets/js/components/namen-leren/NamenLeren.vue#L468-L470

**Comment by cbasje** [comment]
Ja, dat is voor de lichtingen waarbij je de naam op het novietenshirt kunt zien staan. Dit jaar is het niet nodig dus dan kun je bij het selecteren van de lichting ook "Voorkom leesbare namen op foto's" uitzetten.
![Screenshot 2022-09-09 at 14 52 19](https://user-images.githubusercontent.com/45468731/189354255-1b63032f-5014-47b7-8272-180061d66df8.png)

Wellicht is het wel handig om het automatisch uit te zetten nu?

**Comment by asdfCYBER** [comment]
Misschien (geen idee hoe makkelijk dat kan) kan per lichting een andere afkniphoogte worden gebruikt?

**Comment by CodexNine** [comment]
De knop staat nu automatisch uit, en daarmee sluit ik deze issue.
