### ISSUE TITLE
declaraties indienen geeft server error 500

### ISSUE THREAD

**Issue by CodexNine** [csrdelft/csrdelft.nl#1046]
Bij het invullen van een declaratie komt de volgende pop-up:
An exception has been thrown during the rendering of a template ("Asset met naam images/beeldmerk-wit.png bestaat niet.")
Normaliter worden acties nog uitgevoerd als deze error verschijnt (zoals bij het opladen naar het forum) maar hier wordt de declaratie niet ingediend.

**Comment by CodexNine** [comment]
In templates/mail/letter.mail.twig heb ik het volgende aangepast op line 12:
van
`absolute_url(asset_url('images/beeldmerk-wit.png'))`
naar
`absolute_url('images/beeldmerk-wit.png')`

Dit fixte de error en declaraties kunnen weer ingediend worden.

**Comment by cbasje** [comment]
haha damn you, `asset_url()`!
