### ISSUE TITLE
Back-end framework?

### ISSUE THREAD

**Issue by brussee** [csrdelft/csrdelft.nl#110]
Belangrijkste is dat de stek geleidelijk verbeterd moet worden wordt aangezien het niet in 1x kan. Iedereen onderschat onze stek. (Ja, jij dus ook. En ik ook nog vaak.)

**Comment by brussee** [comment]
Belangrijkste is dat de stek geleidelijk verbeterd moet worden wordt aangezien het niet in 1x kan. Iedereen onderschat onze stek. (Ja, jij dus ook. En ik ook nog vaak.)

**Comment by qurben** [comment]
Ik denk dat een backend framework nog wat verder op de roadmap staat. Het liefst heb ik zo veel mogelijk consistentie voordat de stap naar een ander framework wordt gezet.

**Comment by brussee** [comment]
@qurben Precies, helemaal mee eens. Eerst netjes alles consistent en modulair.

**Comment by qurben** [comment]
Overstap naar Symfony is nu in volle gang.

**Comment by qurben** [comment]
Symfony zit nu in een groot deel ingebakken.
