### ISSUE TITLE
Voorpagina werkt niet als fotoalbum map niet bestaat

### ISSUE THREAD

**Issue by pmvz** [csrdelft/csrdelft.nl#1102]
De voorpagina wil niet laden omdat `csrdelft_voorpagina_fotoalbum` niet gevonden wordt. Geen flauw idee wat er precies mis gaat, want PhpStorm heeft wel een volgbaar linkje. Als regel 16 van `voorpagina.html.twig` wordt weggelaten laadt de voorpagina wel, met een foutmelding dat voorpagina_posters ook niet wordt gevonden.

**Comment by qurben** [comment]
`csrdelft_voorpagina_fotoalbum` is een route in `VoorpaginaController` en het lijkt er inderdaad op dat dit faalt als de `voorpagina_posters` cms pagina mist (oftewel in de Fixtures).

**Comment by pmvz** [comment]
Hoe kan ik dit fixen?

**Comment by qurben** [comment]
Oh ik keek verkeerd, hij faalt omdat de map `data/foto/fotoalbum` niet bestaat.

**Comment by qurben** [comment]
Wordt al afgevangen in de tests. Het zou beter zijn als dit niet nodig is tho.
https://github.com/csrdelft/csrdelft.nl/blob/6bc1f1829320b86dfa98671aacb9e1d71f5b5852/tests/lib/BrowserTestCase.php#L85-L88
