### ISSUE TITLE
CSV export van leden is stuk

### ISSUE THREAD

**Issue by qurben** [csrdelft/csrdelft.nl#111]

**Comment by thervh70** [comment]
Is idd stuk, je kunt via de ledenlijst wel een csv bouwen mocht je dat willen

**Comment by qurben** [comment]
Waar is het stuk? In de ledenlijst werkt inderdaad wel.

**Comment by thervh70** [comment]
Menu -> Communicatie -> LedenLijst -> CSV downloaden (knopje in het menu)
Geeft de volgende php file terug: `Unable to run query: Table 'csrdelft.lid' doesn't exist`

**Comment by thervh70** [comment]
Eigenlijk slechts een kwestie van menu item verbergen ;)

**Comment by qurben** [comment]
Gedaan 😄
