### ISSUE TITLE
Subdomain /dies verwijst niet goed door naar de laatste dies.

### ISSUE THREAD

**Issue by Jobkanis** [csrdelft/csrdelft.nl#1145]
Normaal verwijst /dies naar de meest recente diespagina.
De rewrite rule in \htdocs\dies\.htaccess die dit doet overwrite echter de submodules voor /dies/20__.

**Comment by Jobkanis** [comment]
Het gaat om dit bestand: https://github.com/csrdelft/csrdelft.nl/blob/master/htdocs/dies/.htaccess

**Comment by jobvonck** [comment]
gefixt in [7dea897](https://github.com/csrdelft/csrdelft.nl/pull/1163/commits/7dea897fca9a94f19720019759e1a63bb95a4e1a)
