### ISSUE TITLE
Woonoord beheer rechten

### ISSUE THREAD

**Issue by SimonGeb** [csrdelft/csrdelft.nl#1159]
Er zijn problemen met de rechten rondom woondoord beheer.

**Comment by NathanHuisman** [comment]
![image](https://github.com/csrdelft/csrdelft.nl/assets/36598276/40644cd1-7697-452c-ba95-d03b887f56b5)

Dit is waarschijnlijk het probleem. Ik gok dat de refactor van @qurben groep->mag en groep->magLid door elkaar heeft gehaald en allebei heeft vervangen met isGranted

**Comment by NathanHuisman** [comment]
Het gaat om deze refactor: 99469a24e2

**Comment by NathanHuisman** [comment]
Huh, wat raar. Het lijkt alsof de GroepLidVoter nooit gecalld wordt
