### ISSUE TITLE
Weergave zoekresultaten forum

### ISSUE THREAD

**Issue by benjaminkomen** [csrdelft/csrdelft.nl#12]
De zoekresultaten worden momenteel erg vreemd weergegeven, dit is al een aantal jaren zo, sinds Paul dit veranderd heeft. Vroeger werd een lijst met titels van draadjes waar je zoekterm in voorkwam getoond, en een fragment van de post waar het woord in voorkwam met de zoekterm ge-highlight. Momenteel worden er een aantal complete posts van het draadje waar je zoekterm in voorkomt getoond, met een - voor een leek - onmogelijke manier te snappen hoe hij naar dat draadje kan navigeren. Ik kan niet zo snel vinden of dit [hier](https://trac.knorrie.org/csrdelft.nl/timeline) ook gemeld is, maar in ieder geval, lijkt me wel handig om dat te fixen.

**Comment by benjaminkomen** [comment]
Dankjewel voor het fixen, dit is prima.

**Comment by qurben** [comment]
Lijkt me goed om hier nog een keer beter naar te kijken, dingen zoals highlighting en misschien een iets intuitiever zoeksysteem zijn mooie features.

**Comment by benjaminkomen** [comment]
Ja, eens. Eigenlijk wil je meer zoals op de wiki: 
![wiki_zoeken](https://cloud.githubusercontent.com/assets/12815582/16299665/c1a7669c-393b-11e6-9748-b58f12fad21e.png)

**Comment by brussee** [comment]
De huidige search gebruik FTS van MySql en heeft natural language mode.
Dit werkt misschien beter: http://php.net/manual/en/refs.search.php
