### ISSUE TITLE
AccountModel->moetWachten is stuk

### ISSUE THREAD

**Issue by qurben** [csrdelft/csrdelft.nl#13]
De gebruiker moet, als hij moet wachten, altijd 45 seconden wachten.

```php
switch ($account->failed_login_attempts) {
	case 0: $wacht = 0;
	case 1: $wacht = 5;
	case 2: $wacht = 15;
	default: $wacht = 45;
}
```

**Comment by brussee** [comment]
Fix: het is een string en moet worden gecast naar int

**Comment by qurben** [comment]
Fix: break

**Comment by brussee** [comment]
Lol you're right

**Comment by brussee** [comment]
Gefixed: https://github.com/csrdelft/csrdelft.nl/pull/67/commits/e06b42fc8c644d7805e57de3927a027f853b40a4
