### ISSUE TITLE
Kwalikok rechten

### ISSUE THREAD

**Issue by brussee** [csrdelft/csrdelft.nl#130]
Rechten voor kwalificatie:kwalikok

**Comment by brussee** [comment]
Gemaakt in #129

**Comment by thervh70** [comment]
@brussee deze kan dus dicht?

**Comment by brussee** [comment]
@thervh70 Nee, dat kan pas als de oplossing daadwerkelijk werkt in productie (als je een aparte development branch zou hebben, als het daarin werkt, voor een nieuwe release).

**Comment by brussee** [comment]
@thervh70 Met hetzelfde gemak klik je op de merge-knop ;-p
