### ISSUE TITLE
Account rechten

### ISSUE THREAD

**Issue by brussee** [csrdelft/csrdelft.nl#134]
Wachtwoord wijzigen vereist momenteel P_PROFIEL_EDIT, maar sinds de scheiding van Profiel en Account moet dit P_LOGGED_IN zijn.

**Comment by brussee** [comment]
Gefixed in #133

**Comment by thervh70** [comment]
@brussee oftewel deze kan dicht?

**Comment by brussee** [comment]
@thervh70 Nee, eerst het betreffende PR #133 mergen, dan pas ticket sluiten. Sterker nog, dat laatste gaat vanzelf met GitHub op die manier.

**Comment by thervh70** [comment]
@brussee dat gaat alleen als je "fixes #134" vermeld in de PR comment. Op die manier is de reference naar de PR ook snel gemaakt. Zodra je in deze issue zegt: gefixt in ga ik ervanuit dat het al gemerged is.

Ik zal alles even reverten.

**Comment by brussee** [comment]
> dat gaat alleen als je "fixes #134" vermeld in de PR comment.

Of in de commit message.

Voortaan zal ik beide kanten op refereren voor het gemak.

**Comment by brussee** [comment]
@thervh70 Als #170 is gemerged kun je dit issue sluiten.
