### ISSUE TITLE
Mededelingen verbeteren

### ISSUE THREAD

**Issue by brussee** [csrdelft/csrdelft.nl#136]
- [ ] Koppel updates van een ketzer aan het mededelingensysteem
- [ ] en toon deze eventueel alleen aan ingeketzte leden.

Vervaag de grens met mededelingen en forumdraadjes voor de zogenaamde [infodraad] onderwerpen:
- [ ] Geef mededelingen automatisch een apart draadje voor commentaar (koppel mededelingen in families net als groepen, draadje per familie)

**Comment by qurben** [comment]
Mededelingen zijn verwijderd in 25c5a97698e1c7aa428d288f377a76ed87fab082

**Comment by brussee** [comment]
Is dit vanwege een aanpassing van het formele communicatie-plan/document van de vereniging?

**Comment by mathcals** [comment]
De aanleiding hiervoor is vooral het feit dat mededelingen eigenlijk nooit gebruikt werden (ongeveer 1 keer per jaar). De mededelingenfunctionaliteit voegt ook niet zo veel toe om dat er ook al het forum belangrijk is. Daarnaast zaten er een aantal mogelijke veiligheidsrisico's in de implementatie van mededelingen.
