### ISSUE TITLE
Ketzers aanmaak "tovenaar"

### ISSUE THREAD

**Issue by thervh70** [csrdelft/csrdelft.nl#139]
Veel leden klagen over het feit dat ketzers bouwen soms een lastig werkje kan zijn. Om fouten te voorkomen en veel leden een duwtje in de juiste richting te geven moet er een wizard komen om de leden door dit proces heen te helpen.

De tovenaar moet ieder vakje los behandelen of in ieder geval overzichtelijk uitleg geven.

**Comment by brussee** [comment]
https://github.com/csrdelft/balins-adventure/issues/51
http://git.inkworks.nl/csr/csrdelft.nl/issues/32

**Comment by thervh70** [comment]
Duplicated.
