### ISSUE TITLE
MaaltijdAbo novieten verticale:X

### ISSUE THREAD

**Issue by brussee** [csrdelft/csrdelft.nl#140]
Ik zie in het maaltijdabonnementenbeheeroverzicht allemaal waarschuwingen staan over novieten met een niet-toegestane abonnement op verticale X maaltijden en verder niets.

**Comment by brussee** [comment]
Het lijkt er sterk op dat iemand per ongeluk alle novieten een Verticale:X maaltijdabonnement heeft gegeven via de beheerinterface. Deze kunnen ze zelf uitzetten, maar het is beter als iemand met P_MAAL_MOD deze fout hersteld.

**Comment by qurben** [comment]
Deze fout is onderhand hersteld
