### ISSUE TITLE
DataTable knopjes zonder randje

### ISSUE THREAD

**Issue by brussee** [csrdelft/csrdelft.nl#142]
De knopjes van DataTable hebben geen border meer, moet dezelfde zijn als de standaard knoppen.

**Comment by qurben** [comment]
Op welke plek komt dit voor? Bij de groepen werkt het in ieder geval nog wel
![](http://i.imgur.com/KNx3l8d.png)

**Comment by brussee** [comment]
Ik heb de OWee layout, waarschijnlijk ligt het daaraan.

**Comment by qurben** [comment]
Fixed in 9f714da
