### ISSUE TITLE
Agenda categorieën GUI

### ISSUE THREAD

**Issue by brussee** [csrdelft/csrdelft.nl#154]
Categorieën met kleurcodes en instelbare filters voor agenda-items om snel het verschil te maken tussen verenigingsactiviteiten en andere zaken. (Kijk eventueel naar forum en mededelingen voor inspiratie.)

**Comment by qurben** [comment]
Dit is onderhand gefixt, verschillende soorten activiteiten hebben verschillende kleuren.
