### ISSUE TITLE
Externe libs (js & css)

### ISSUE THREAD

**Issue by qurben** [csrdelft/csrdelft.nl#157]
Zorg ervoor dat externe javascript en css libraries van een externe bron worden gedownload, zodat de repo kleiner wordt en het duidelijk is welke bestanden door ons geschreven zijn.

**Comment by brussee** [comment]
Voor zover ik weet kan dit al met HtmlPage->addScript(url, remote=true);

**Comment by qurben** [comment]
Ik ben geen fan van CDN's, in ieder geval niet als er geen centrale lijst is met libs+versies

**Comment by qurben** [comment]
Heeft te maken met #3

**Comment by Manduro** [comment]
Ik kan [npm](https://www.npmjs.com) aanraden voor het managen van front-end libraries & [webpack](http://webpack.github.io) voor het bundelen ervan.

**Comment by brussee** [comment]
https://hackernoon.com/how-it-feels-to-learn-javascript-in-2016-d3a717dd577f#.gupeqdoie

**Comment by thervh70** [comment]
@brussee #107

**Comment by qurben** [comment]
Een optie is om npm te gebruiken en Travis (oid) in te zetten om deze dependencies te downloaden.

Deze tussenstap moet dan wel gebouwd en getest worden en er moet iets komen voor programmeurs om lokaal te runnen zonder dat live en dev te veel van elkaar verschillen.

**Comment by qurben** [comment]
Zoals het nu werkt in de stek is het best wel chill en best wel snel, er is ook geen extra software nodig om het te laten werken. Het liefst komt er een oplossing waarbij je niet te veel hoeft in te leveren.

**Comment by brussee** [comment]
https://trends.builtwith.com/#top10kChanges

**Comment by qurben** [comment]
# Npm met staging op GitHub

Installeer dependencies met `npm`, programmeurs gebruiken `npm install`. Een push naar master triggert Jenkins (o.i.d.). Die maakt een build en zet deze in de staging branch op github. Op Syrinx kan nu gepulled worden, alle javascript is gedownload, alles kan ook gepackaged worden.

## Pluspunten
* Flexibiliteit, je doet deploy nog steeds zelf

## Minpunten
* Langzaam, hotfix niet meer mogelijk

**Comment by qurben** [comment]
# Npm met deploy via CI

Installeer dependencies met `npm`, programmeurs gebruiken `npm install`. Een push naar master triggert CI. Die maakt een build en zet deze op Syrinx. Migraties enzo worden ook gerund bij het deployen, alles gebeurt automatisch.

## Pluspunten
* Consistente deploys.
* Hotfixes komen zo online te staan.

## Minpunten
* Phinx kan niet volledig met orm overweg.

**Comment by Boudewijn26** [comment]
Ik zou even wachten tot npm v5, het wachten duurt anders bijzonder lang.

**Comment by Manduro** [comment]
Die is er al!

**Comment by qurben** [comment]
# Package manager met handmatige deploy

Installeer dependencies met `npm`/`bower`, programmeurs gebruiken `npm install`/`bower install`. Bij deploy moet dit ook gebruikt worden.

## Pluspunten
* Duizend controle

## Minpunten
* Je moet vet lang op syrinx zitten en syrinx moet node geinstalleerd hebben.

**Comment by qurben** [comment]
Gisteren :joy:

**Comment by qurben** [comment]
# Zelf een deploy tool bouwen

Ja mooi! In PHP een soort mini-npm bouwen.

## Pluspunten
* Dertienduizend controle
* Nauwelijks overhead
* We hebben het compileren van (less) bestanden al ingebouwd

## Minpunten
* Moet onderhouden worden
* Is niet triviaal om te doen

**Comment by brussee** [comment]
^ Pluspunten: zeer leerzaam!

**Comment by Boudewijn26** [comment]
@Manduro, klopt, maar nog niet voor alle distro's gedownstreamt.

**Comment by qurben** [comment]
# Package manager met build in repo

Zorg ervoor dat de build ook in de repo gezet wordt. Deze gooi je dan bij je PR er in of stuur je mee in een nieuwe PR. (kan eventueel ook door CI geautomatiseerd worden)

## Pluspunten

* Veel controle
* Deploy op Syrinx is simpel en snel: `git pull` of `git pull && vendor/bin/phinx migrate`

## Minpunten

* Omslachtig om iedere keer een build te maken.
