### ISSUE TITLE
Bug: maaltijd verwijderen via maaltijdenbeheer

### ISSUE THREAD

**Issue by thervh70** [csrdelft/csrdelft.nl#158]
Dit lukt simpelweg niet..

Er is een knopje met een vinkje. Die kun je aanvinken maar dan gebeurt er vrij weinig. De url van de knop invullen in de urlbalk (csrdelft.nl/maaltijdenbeheer/verwijder/1744) geeft een "Geen Toegang" beeld.

**Comment by qurben** [comment]
Het verwijderen van maaltijden is een 'waar op het knopje klikken' probleem.

**Comment by qurben** [comment]
Moet inderdaad gefixt worden, de 'Geen Toegang' is omdat een maaltijd verwijderen met een POST request gebeurd. (gok ik)

**Comment by thervh70** [comment]
Neem je dit mee in de maaltijd refactor @qurben ?

**Comment by qurben** [comment]
Nee, dit ga ik nu fixen

**Comment by qurben** [comment]
Is namelijk klein en vervelend

**Comment by brussee** [comment]
@thervh70 Dit was een feature request van de MaalCie om meerdere dingen tegelijk te kunnen verwijderen: shift-klik op de checkbox en deleten met de knop.

**Comment by thervh70** [comment]
@brussee Prima, maar ik zag de verwijder knop nergens!

**Comment by brussee** [comment]
@thervh70 De checkbox zat in de knop, net als bij maaltijd-ketzers.

**Comment by thervh70** [comment]
@brussee Ja, maar klikken veranderde niets. Was er geen "opslaan" knop?

**Comment by brussee** [comment]
Als klikken op de knop, met optioneel meerdere checkboxen aan, niet werkt dan was dat inderdaad stuk. De ``range`` zorgde voor een .click() op alle aangevinkte knopjes bij het klikken op 1 van de knopjes, dwz buiten de checkbox.
