### ISSUE TITLE
Single issue tracker

### ISSUE THREAD

**Issue by brussee** [csrdelft/csrdelft.nl#16]
I've already migrated all *relevant Trac tickets* to the other repo some time ago, maybe you can move them?
I also included a backlink for reference and context, existing discussion, etc.

https://github.com/csrdelft/balins-adventure/issues/created_by/brussee

**Comment by qurben** [comment]
Trac met haar tickets en wiki zijn nog steeds referentie. Alles in een keer kopieren zorgt vooral voor chaos. (moet ook nog over vergaderd worden)
