### ISSUE TITLE
Kringcoach boolean in Profiel

### ISSUE THREAD

**Issue by thervh70** [csrdelft/csrdelft.nl#162]
Verzoekje van Am. Vab. Mag lijken op de boolean voor verticaleleider. Op dit moment staat het anders opgeslagen.
- [x] veld veranderen in `Profielview`
- [x] DB checken en potentiele wijzigingen doorvoeren

**Comment by brussee** [comment]
Zoals het was: kringcoaches kunnen (1) van andere verticalen zijn, (2) meerdere andere verticalen coachen en (3) gezamenlijk coachen.
Als je het een boolean maakt zoals verticaleleider ben je al deze functionaliteit kwijt. De huidige vab. heeft waarschijnlijk geen situatie meegemaakt als bovenstaande in afgelopen jaren.

**Comment by Erackron** [comment]
(1) Is momenteel inderdaad niet het geval
(2) Dat is met de huidige manier hoe het in de stek zit ook niet mogelijk
(3) Dat kan met deze boolean nog steeds. Meerdere mensen per verticale kunnen de boolean op true hebben

**Comment by thervh70** [comment]
@Erackron Ik heb een mail gestuurd naar de vab.

**Comment by thervh70** [comment]
Mail terug: altijd een lid uit de verticale, anders oudlid uit de verticale. Mogelijk springt de VAb zelf in als coach, maar daar hoeft het systeem geen rekening mee te houden.

Oftewel, volgens mij voldoet een simpele boolean.

**Comment by brussee** [comment]
@qurben
