### ISSUE TITLE
Betere streeplijstgeneratortool

### ISSUE THREAD

**Issue by qurben** [csrdelft/csrdelft.nl#167]
Er is een streeplijstgenerator op https://csrdelft.nl/tools/streeplijst.php, deze is helaas best wel karig.

Mooie dingen die een streeplijstgenerator kan gebruiken
- [ ] Interactieve manier om gegenereerde lijst te tweaken
- [ ] Presets (bijv. SocCie assortiment, beperkt SocCie assortiment, 1 lege kolom)
- [ ] Streeplijst op basis van ketzer of groep (weekeind inschrijvingen bijvoorbeeld) (!)
- [ ] Mogelijkheid om lege velden achter de lijst te plaatsen voor eventuele extra streepbare mensen
- [ ] Mogelijkheid om prijzen te vermelden (Brussee)

Extra:
- [ ] Arbitraire groep mensen (Je kan natuurlijk ook eerst een groep maken)
- [ ] Terugkoppeling en aan CiviSaldo hangen :joy:
  - Auteur kan de streeplijst opnieuw opvragen, invullen en afrekenen

**Comment by brussee** [comment]
Als je wilt kijk dan ter inspiratie naar het ERM van #105. Daarin worden streeplijsten dynamisch aan producten en prijslijsten gekoppeld. Een simpele DataTable doet dan puntje 1 en twee lijsten naast elkaar (productenlijst links, streeplijst rechts) met een btn_addAll doet punt 2.

Als lid vind ik het prettig als er wel een prijs op de streeplijst vermeld wordt, tenzij die achteraf bepaald wordt.

**Comment by thervh70** [comment]
Koppeling naar CiviSaldo is prachtig maar écht nog niet aan de orde.
