### ISSUE TITLE
HTML cleanup

### ISSUE THREAD

**Issue by brussee** [csrdelft/csrdelft.nl#171]
Er zitten nog veel HTML examples in DataTable extensions:

``rm -rf htdocs/assets/layout/js/datatables/extensions/*/examples``

Daar komt de HTML 26.5% vandaan in github language details van deze repo.

**Comment by thervh70** [comment]
`Showing 108 changed files  with 0 additions and 19,407 deletions.`

Hulde Paul voor het vinden van deze overbodige files.

**Comment by qurben** [comment]
Fixed in a8b851e
