### ISSUE TITLE
Formulier in CommissieVoorkeuren naar Formulier class

### ISSUE THREAD

**Issue by qurben** [csrdelft/csrdelft.nl#18]
In `lib/view/CommissieVoorkeurenView.class.php`

**Comment by brussee** [comment]
Overzicht: https://trac.knorrie.org/csrdelft.nl/milestone/Form%20refactor%20front-end

**Comment by brussee** [comment]
Original milestone: https://trac.knorrie.org/csrdelft.nl/query?group=status&milestone=Form+refactor+front-end

**Comment by qurben** [comment]
Gefixt in #366
