### ISSUE TITLE
Leeftijd verjaardagen in Agenda stuk

### ISSUE THREAD

**Issue by thervh70** [csrdelft/csrdelft.nl#182]
Reeds door meerdere leden gemeld: de agenda geeft de leeftijd van iemand aan die jarig is, maar die leeftijd klopt soms niet.

Volgens Ama. van den Berg sr. is het vanaf januari 2017 structureel 1 jaar te weinig bij iedereen.

**Comment by qurben** [comment]
Haha, wie anders

**Comment by qurben** [comment]
De leeftijd is ieder jaar hetzelfde

**Comment by qurben** [comment]
Als je over 10 jaar kijkt klopt het ook niet.
