### ISSUE TITLE
Laadtijd home pagina

### ISSUE THREAD

**Issue by Vennik** [csrdelft/csrdelft.nl#186]
De laatste tijd valt mij op de laadtijd van de home pagina erg hoog is.
Dit valt vooral op, omdat de animaties pas beginnen als alles geladen is.

(Verder zit het wachtwoord vergeten knopje iets te dicht op het inloggen knopje, dus op mijn telefoon klik ik heel vaak net scheef.)

**Comment by qurben** [comment]
Er wordt helaas nog niets gecached, dit zal best wel wat schelen.

**Comment by TimvdLippe** [comment]
Using the Chrome dev Tools with 3G throttling, it took a full 1.1 minute to load the webpage and start the animations. The `DomContentLoaded` event is fired at 8.32s. The target for fully loading a page should be 3 seconds.

Looking at the resources being loaded in page load, I see that a big chunk is spent on downloading images. However, these images are not visible until after the animation has kicked in and the actual content is shown. A simple optimization would be to compress the images and lazy load them once they are in the viewport.

For example the Logo.svg is a whopping 701 KB. This seems largely affected by the `<font>` inside the svg. Can this font be removed?

Secondly there is a huge chunk of javascript loaded inside `base.js` for a total of 431 KB. Solutions such as [code splitting](https://www.youtube.com/watch?v=QH94CXVv3UE) or employing [the PRPL pattern](https://www.polymer-project.org/1.0/toolbox/server#prpl-pattern) (this pattern is agnostic of framework, so not Polymer-specific) would probably reduce the total javascript size. E.g. only load the code for the route that is currently loaded by the user and lazy-load all other routes using `requestIdleCallback`.

Also note that a full page load was 5.6 MB, where the target should be < 1 MB. All images combined are 4.1 MB and all javascript is 1.2 MB. Combined these files provide the most potential for a performance improvement.

For repeat visits, installing a [service-worker](https://developers.google.com/web/fundamentals/getting-started/primers/service-workers) would significantly reduce the amount of network content downloading. You can very easily generate a sw with [sw-precache](https://github.com/GoogleChrome/sw-precache).

For some more tips and tricks you can use [PageSpeed Insights](https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Fcsrdelft.nl%2F). This shows for example that images are not compressed and no caching is in place for static assets such as js and images. Also defer loading stylesheets and javascript files which are non-blocking for the actual content on the homepage, e.g. jQuery files and google fonts.

Lastly you can see [this WebPagetest report](https://www.webpagetest.org/result/161222_7H_1BME/) which assets are taking very long to load and in which order the network requests were triggered.

**Comment by Manduro** [comment]
Start gemaakt in #231. Todo, op volgorde van prio:

- [x] Logo SVG verkleinen
- [x] Vaste foto's verkleinen
- [x] Externe (iframe) scripts vertraagd laden
- [ ] Compressie inschakelen voor `tools/js.php?l=layout-owee&m=general&1478442408`
- [ ] Alle inline scripts (in login bijv.) naar js files, en dan...
- [ ] ...`tools/js.php` uit `<head>` naar einde `<body>`
- [ ] Foto's uit fotoalbum (automatisch) verkleinen naar ~500px breed
- [ ] Foto's lazy loaden bij naderen viewport, dan pas in animeren
- [ ] Vaste foto's nog meer verkleinen (vanuit high res origineel comprimeren)
- [ ] Webfonts preloaden
- [ ] Cache tijd instellen voor `assets/...` en `plaetjes/...`
- [ ] Compressie inschakelen voor `assets/layout-owee/plaetjes/Logo.svg`

**Comment by qurben** [comment]
Onderschat 
> Alle inline scripts (in login bijv.) naar js files, en dan...

niet, login maakt gebruik van de formulier klasse die door de hele stek gebruikt wordt. Dit zou eruit gehaald moeten worden of de hele formulier klasse moet gerefactored worden.

Dat laatste heeft mijn voorkeur, maar ik zie nog niet voor me hoe dat eruit zou moeten zien.

**Comment by TimvdLippe** [comment]
Glad action is being taken to resolve the performance issues. Ping me when most of the work has been finished, curious to make a comparison in the end 😄

**Comment by qurben** [comment]
Het loginvenster verplaatst niet meer sinds 6902f01b81e204511c9a8b641a6094c71f0534bc

**Comment by qurben** [comment]
Webpagetest geeft A's voor alle onderdelen behalve CDN https://www.webpagetest.org/result/181228_XG_d582f73e2840f25c9fe6cc5c4d0f3584/

Pagespeed geeft een 95 https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Fcsrdelft.nl%2F

Verbeteringen die zijn doorgevoerd:

 - [x] Laad de webfonts niet van Google, zodat eigen caching kan worden ingesteld
 - [x] Laad alleen de core css op de voorpagina
 - [x] Laad alleen jquery en jgallery op page load
 - [x] minify js & css
 - [x] zet cache headers van alle assets

Verbeteringen die nog kunnen worden doorgevoerd:

 - [ ] Fonts preloaden
 - [ ] Script tag naar einde pagina (en alle scripts uit de body halen) of `defer` gebruiken
 - [ ] SVG compressen met gzip
 - [ ] Minder fonts gebruiken
 - [ ] Laad alleen zinnige css als de pagina geladen wordt

**Comment by qurben** [comment]
Dit is iets wat tot in de oneindigheid verbeterd kan worden. Op dit moment is de laadtijd best wel prima.

**Comment by Vennik** [comment]
Niet meer op 95, maar op 79 nu :)

**Comment by qurben** [comment]
Ik denk dat ik toen naar de desktop variant keek. Die staat nu op 99.
