### ISSUE TITLE
TODO: invalidate compromised token

### ISSUE THREAD

**Issue by brussee** [csrdelft/csrdelft.nl#194]
https://github.com/csrdelft/csrdelft.nl/blob/master/lib/configuratie.include.php#L109

```
// Use HTTP Strict Transport Security to force client to use secure connections only
if (FORCE_HTTPS) {
	if (!(isset($_SERVER['HTTP_X_FORWARDED_SCHEME']) && $_SERVER['HTTP_X_FORWARDED_SCHEME'] === 'https') && MODE !== 'CLI') {
		// check if the private token has been send over HTTP
		$token = filter_input(INPUT_GET, 'private_token', FILTER_SANITIZE_STRING);
		if (preg_match('/^[a-zA-Z0-9]{150}$/', $token)) {
			//TODO: invalidate compromised token
		}
		// redirect to https
		header('Location: ' . CSR_ROOT . REQUEST_URI, true, 301);
		// we are in cleartext at the moment, prevent further execution and output
		die();
	}
}
```

**Comment by qurben** [comment]
Gefixt in 8a76e9b dit stukje code kan op syrinx niet uitgevoerd worden, maar eventuele configuratie op een nieuwe server zou dit stukje code aan mee kunnen helpen.

**Comment by brussee** [comment]
Nice! Als je heel strikt bent is ook de OneTimeToken kwetsbaar, want die blijft geldig tot de actie is volbracht (flawed by design) of 'ie expired.

**Comment by brussee** [comment]
Naast loggen misschien een mailtje sturen "uw token is ge-reset vanwege beveiligingsredenen" oid

**Comment by brussee** [comment]
En wat als $account false/null is?

**Comment by thervh70** [comment]
@qurben, @brussee  is het nou gefixt? zo ja, mag je deze sluiten. Evt. een nieuw issue openen met duidelijke beschrijving die voortvloeit uit de comments.

**Comment by brussee** [comment]
De mogelijke nullpointer wordt nog steeds niet netjes afgevangen.

**Comment by thervh70** [comment]
@brussee niet netjes, betekent dat dat het een security issue zou kunnen worden?

**Comment by qurben** [comment]
Het kan zijn dat een token geinvalidate wordt, terwijl de token niet meer bestaat.

Het is alleen niet mogelijk op Syrinx dat er een request over http gedaan wordt, deze komt nooit aan op de stek. Alle requests naar http worden vroegtijdig geredirect naar https. Je zou hier naar de referer moeten kijken. 

Daarnaast doet dit zich alleen voor als de gebruiker die een mailtje krijgt de url kopieert en zonder https in de urlbalk plakt. Ik zie geen andere manier waarop dit zou kunnen gebeuren.
