### ISSUE TITLE
HSTS disabled for www.csrdelft.nl

### ISSUE THREAD

**Issue by brussee** [csrdelft/csrdelft.nl#195]
Voor het domein www.csrdelft.nl is HSTS nog steeds disabled (sinds een of andere commit, zie forumdraadje in PubCieforum).

Dat zorgt ervoor dat eventuele tokens plain text over de lijn gaan en dat wil je niet. Zie ook #194

**Comment by qurben** [comment]
Ik heb Knorrie hier een mailtje over gestuurd.

**Comment by qurben** [comment]
De flow is nu `http://www.csrdelftnl -> https://www.csrdelft.nl -> https://csrdelft.nl`. Nu zet https://www.csrdelft.nl HSTS aan.
