### ISSUE TITLE
Maak het mogelijk om meerdere emails te hebben

### ISSUE THREAD

**Issue by thervh70** [csrdelft/csrdelft.nl#203]
Op dit moment is er sprake van data duplication in de DB. Voor zover ik weet (mn gevoel kan fout zijn) is hier geen duidelijke reden voor.

Het gaat om de `email` kolom die zowel in `profiel` als `account` voorkomt.

**Comment by brussee** [comment]
Account heeft een primary email nodig en profiel heeft potentieel onbeperkt email velden. Net zoals potentieel onbeperkt adressen en telefoonnummers etc.
Dit is alleen nu halfbakken geïmplementeerd, 1e stap bij scheiding van account en profiel (voormalig almighty lid-object dat ook niet-leden waren).

**Comment by thervh70** [comment]
In dat geval zou het dus zo moeten zijn dat een profiel 0...n altemails heeft. Theoretisch gezien is dat mogelijk maar in de praktijk denk ik dat veel leden slechts 1 mailadres gebruiken. Bovendien hebben ze er waarschijnlijk geen behoefte aan om al hun emailadressen met de civitas te delen.

Hetzelfde zou je kunnen zeggen voor bankrekeningen waar ik er persoonlijk ook meerdere van heb. Op die manier zou je de DB onnodig complex maken met extra tabellen.

**Comment by qurben** [comment]
Gefixt in #632, emails in een andere tabel duwen wordt een losse issue
