### ISSUE TITLE
Verwijder afbeeldingen uit mededeling

### ISSUE THREAD

**Issue by qurben** [csrdelft/csrdelft.nl#21]
Verwijder de afbeelding van een mededeling als de mededeling verwijderd wordt of als er een nieuwe afbeelding wordt gekozen.

**Comment by brussee** [comment]
Er is een mooie ImageField in FormFields die heel veel al doet.

**Comment by thervh70** [comment]
@qurben is dit niet al gefixt in #11 ?

**Comment by qurben** [comment]
Nee, #11 is relevant, maar lost dit probleem niet op

**Comment by qurben** [comment]
Mededelingen zijn verwijderd in 25c5a97698e1c7aa428d288f377a76ed87fab082
