### ISSUE TITLE
BBCode parser uitbreiding

### ISSUE THREAD

**Issue by thervh70** [csrdelft/csrdelft.nl#212]
Oud issue van de trac.

Uitbreidingen voor courant en forum.
- [ ] automatisch taggen binnen tekst
- [x] mailto tags

**Comment by brussee** [comment]
[email]mailto[/] bestaat al, bedoel je dat?

**Comment by qurben** [comment]
Er zijn op dit moment geen specifieke behoeften aan uitbreidingen aan de bbcode parser.

**Comment by brussee** [comment]
[lid=] wordt veel gebruikt en zou een melding moeten geven (opt-out), apart ticket aanmaken?

**Comment by qurben** [comment]
Dat is een feature die totaal los staat van deze veranderingen in de bb parser, dus sowieso een andere ticket voor maken.

**Comment by brussee** [comment]
done: #275
