### ISSUE TITLE
Logging verbeteren / uitschakelen

### ISSUE THREAD

**Issue by thervh70** [csrdelft/csrdelft.nl#215]
Oud issue van de trac.

De log tabel barst regelmatig uit zn voegen. We kunnen een stuk code schrijven die structureel oude entries weggooit, of we kunnen alle logging uitzetten.

Zelf zie ik er niet echt het grote nut van in (behalve statistieken), meningen?

**Comment by qurben** [comment]
Logs ouder dan twee maanden worden automatisch weggegooid sinds b07f9f30de7dd314ab17436a74df2af3350c8a5d

Het kan handig zijn om wat logging te hebben voor als er gekke dingen gebeuren.

**Comment by thervh70** [comment]
top! dan sluit ik dit puntje meteen weer.
