### ISSUE TITLE
Forum api

### ISSUE THREAD

**Issue by Manduro** [csrdelft/csrdelft.nl#22]
Forum API voor gebruik door de app.
Punt van aandacht: bb-codes.

### Views

- [ ] Lijst forumdelen `GET api/2.0/forum`
- [x] Recente berichten `GET api/2.0/forum/recent?offset=0&limit=20`
- [ ] Lijst draadjes forumdeel `GET api/2.0/forum/deel/:id?offset=0&limit=20`
- [x] Lijst berichten in draadje `GET api/2.0/forum/onderwerp/:id?offset=0&limit=20`

### Actions

- [ ] Draadje aanmaken `POST api/2.0/forum/onderwerp`
- [ ] Bericht plaatsen `POST api/2.0/forum/onderwerp/:id`

**Comment by brussee** [comment]
Maak een geautomatiseerde representatie (JSON serializer) van PersistentEntity en you are golden. Ga niet met de hand je api specificeren zou ik zeggen, kijk naar hoe de database nu automatisch gemigreerd kan worden met de persistent_attributes etc.

**Comment by brussee** [comment]
Het maken van een volledige JSON API voor de hele stek is denk ik een mooie kans om parallel te ontwikkelen met je favoriete en toekomstbestendige framework (uiteraard in overleg met knorrie).
Hoe zit het met het werk in django van vorig jaar? @Manduro heeft daar veel ervaring mee win-win!

**Comment by thervh70** [comment]
@Manduro dit heb je inmiddels gedaan toch? Of was dat nog niet volledig?

**Comment by Manduro** [comment]
@thervh70 Alleen deels. Heb even een checklist gebouwd hierboven.
