### ISSUE TITLE
CSS bg-image preloading

### ISSUE THREAD

**Issue by thervh70** [csrdelft/csrdelft.nl#225]
Oud issue van trac.

De forumknopjes sluiten, volgen en verbergen knipperen doordat css :hover pseudo-selector geen preloading doet voor de veranderen de background-image.

**Comment by qurben** [comment]
Dit voorbeeld is niet relevant meer, omdat we een spritesheet gebruiken voor de icons. Het preloaden van dit soort dingen is wel jeuk.

**Comment by qurben** [comment]
Niet echt relevant op dit moment
