### ISSUE TITLE
Layout 2 slopen

### ISSUE THREAD

**Issue by thervh70** [csrdelft/csrdelft.nl#232]
Voor zover ik weet is layout-owee de huidige layout van de externe stek. Daarentegen zijn er nog veel plaetjes te vinden in de repo van layout2 (in assets).

Ik ben van mening dat layout2 eruit mag en dat hij dan nog wel in het versiebeheer blijft hangen voor het geval we hem nog een keer nodig hebben. Meningen?

**Comment by thervh70** [comment]
Update: er zijn 2 plaetjes sets in de repo. Zowel in assets als in de bovenstaande map.

**Comment by qurben** [comment]
Zodra er is besloten wat de externe stek wordt (ik ben voor #144) kan in principe `layout2` verwijderd worden.

**Comment by thervh70** [comment]
Ik vind hem echt mooi. En bovendien: hij werkt. Volgensmij is layout2 op sommige paginas wel eens wisselvallig.

Dit ontwerp is ook wel iets waar f.t. OWeeCies iets mee kunnen om de stek te pimpen voor een nieuwe OWee

**Comment by qurben** [comment]
Ik zal #144 omschrijven om er identiek uit te zien als de huidige stek.
