### ISSUE TITLE
[bijbel] bbcode stuk

### ISSUE THREAD

**Issue by brussee** [csrdelft/csrdelft.nl#233]
"/zoeken" moet uit de link, dan werkt het weer.

Voorbeeld:

https://www.debijbel.nl/bijbel/zoeken/NBV/Romeinen%2014:%2013-15

https://www.debijbel.nl/bijbel/NBV/Romeinen%2014:%2013-15

**Comment by thervh70** [comment]
Fixed in 561e7683949d2378d85349f8e6fde30aab8e7bdf
