### ISSUE TITLE
Bouw nieuwe Roodschopper

### ISSUE THREAD

**Issue by thervh70** [csrdelft/csrdelft.nl#235]

**Comment by mathcals** [comment]
Één van de aanbevelingen van Soccie 2018-2019 was 'Denk na over een geautomatiseerd schopsysteem voor leden die rood staan'. Dus misschien is hier toch behoefte aan.

**Comment by qurben** [comment]
Het lijkt me goed om de roodschopper opnieuw te bouwen, het is een redelijk duidelijk afgebakend project.

En misschien is het goed om aan de o.t. SocCie-F, h.t. SocCie-F, Fiscus en h.t. MaalCie-F te vragen of er nieuwe eisen zijn aan dit systeem.

**Comment by mathcals** [comment]
Ja, dat denk ik ook. De oude code was ontzettend gebeund volgens mij.
