### ISSUE TITLE
Framework als dependency

### ISSUE THREAD

**Issue by qurben** [csrdelft/csrdelft.nl#241]
Ik denk dat het een goed idee is om framework als externe dependency te laden. Verandering aan het framework zijn schaars, maar hebben veel impact. Daarnaast is het op sommige plekken niet duidelijk of code van het framework is omdat er op allerlei plekken 'framework' mappen zijn.

Opties hier zijn: Laden via Composer, laden als sub-module of het framework een eigen map geven.

Laden via composer en autoloaden met psr4 is hier denk ik heel erg haalbaar en misschien ook wel de gewenste oplossing. Bij dagelijks geklus hoeven er geen updates te zijn aan het framework. Het loskoppelen maakt het ook mogelijk om het Framework te testen, omdat het hier om een tiental klassen gaat is dit goed te overzien. Deze klassen zijn wel de belangrijkste in de hele stek en het is belangrijk dat alle logica erin klopt.

Er zijn (voor zo ver ik nu zie) twee verwijzingen van Framework naar iets anders, dat zijn de memcache en de MySQL configuratie. De cache en database moeten dus worden doorgegeven naar het framework bij initialisatie.

Plekken waar het framework op dit moment bestaat:
```
/lib/model/framework
/lib/model/entity/framework
```
*In `controller` staat ook nog een framework map, maar dat is een ander framework. Die we overigens er ook naar een dep kunnen bouwen.*

**Comment by thervh70** [comment]
@qurben is dit niet inmiddels gemerged? Of omvat dit issue meer dan dat?

**Comment by qurben** [comment]
Klopt.

**Comment by qurben** [comment]
Zie #244
