### ISSUE TITLE
Corvee-overzicht en rooster zijn stuk

### ISSUE THREAD

**Issue by brussee** [csrdelft/csrdelft.nl#247]
HTTP 500

**Comment by brussee** [comment]
https://csrdelft.nl/corvee en de varianten van mijn corvee en corvee-overzicht doen het nog steeds niet bij mij.

Check ook even de url in het menu, want ik zag dat je de hardcoded menu's had aangepast van het maalcie-systeem. Tip: maak dat menu ook dynamisch: layer3 zeg maar

**Comment by qurben** [comment]
Ik zie het

**Comment by qurben** [comment]
Fixed in ecb723

**Comment by brussee** [comment]
>https://csrdelft.nl/corvee en de varianten van mijn corvee en corvee-overzicht doen het nog steeds niet bij mij.
>
>Check ook even de url in het menu, want ik zag dat je de hardcoded menu's had aangepast van het maalcie-systeem. Tip: maak dat menu ook dynamisch: layer3 zeg maar

Nog steeds... (op productie)

**Comment by qurben** [comment]
Is nu helemaal verholpen

**Comment by brussee** [comment]
Nog 1 ding: een niet-bestaande url geeft een 500 ipv 404.

**Comment by qurben** [comment]
404's bestaan niet op de stek 😛. Die 500's worden al een tijd gegeven als er iets mis gaat. Ooit werden excepties opgevangen denk ik, maar dat is nu al een tijd niet meer zo.

Zodra de frontend van het corveesysteem aan de beurt is voor refactoring wordt hier naar gekeken.

**Comment by brussee** [comment]
:cry: Ik had een mooie exception handler gemaakt die de pubcie mailde als er iets kapot ging met stacktrace etc.

**Comment by qurben** [comment]
Oh, dat werkt nog steeds hoor! Ik ben er nog heel erg blij mee, heb al een aantal keer gehad dat ik iemand kon berichten dat z'n probleem verholpen was zonder dat diegene had geklaagt. De presentatie naar de gebruiker laat alleen nog wel wat te wensen over.
