### ISSUE TITLE
Live feed van whatsappgroep 

### ISSUE THREAD

**Issue by qurben** [csrdelft/csrdelft.nl#251]
Het zou mooi zijn als er op de stek een live feed te zien zou zijn van de huidige discussies in whatsapp.

**Comment by brussee** [comment]
Maak de gesprekken feature van de stek groot met een eigen app, dan kan alles.

**Comment by thervh70** [comment]
Ik denk dat concureren met whatsapp een onbegonnen zaak is.

**Comment by brussee** [comment]
Ik denk dat whatsapp niet hetzelfde dacht als u wat betreft Facebook messenger.

**Comment by qurben** [comment]
Ik denk dat wat @brussee oppert wel een optie is in de verre toekomst. We zijn alleen niet klaar om zulk soort dingen te supporten. Het idee waar ik met deze ticket mee kwam is slechts een kleine extensie op het forum.

De haalbaarheid van whatsappintegratie is iets waar we nog wel op moeten wachten (als het er ooit komt).

**Comment by brussee** [comment]
https://xkcd.com/1810/

**Comment by qurben** [comment]
Prioriteit 0
