### ISSUE TITLE
Lustrum stek

### ISSUE THREAD

**Issue by Manduro** [csrdelft/csrdelft.nl#26]
De oude lustrum stek, te vinden op https://csrdelft.nl/lustrum, staat niet in de repo. De dies stek weer wel. Wat is het beleid hiervoor?

Ik zou hier graag een simpele pagina op knallen. Als ik die simpelweg toevoeg in `htdocs/lustrum` weet ik niet wat er op de server gebeurt, aangezien daar blijkbaar nog iets is achtergebleven.

**Comment by thervh70** [comment]
`htdocs/lustrum` bestaat niet op de server. Ik ga kijken waar die pagina vandaan komt.

**Comment by thervh70** [comment]
@Manduro Aha! https://csrdelft.nl/wiki/lustrumcie:webstek#hosting_csrdelftnl_lustrumcie jullie hebben kennelijk zelf toegang tot dat gedeelte van de stek.

**Comment by Manduro** [comment]
Hmm, ik kan alleen geen wachtwoord vinden in onze overdracht. Is het nog handig dit zo te houden, of beter om dit in de repo te hebben zoals de dies stek?

**Comment by thervh70** [comment]
#28 gaat ervoor zorgen dat we al die stukken code naar GitHub gaan halen. Ik heb al gereageerd dat dit ook met de lustrum stek moet gaan gebeuren. Als dat gelukt is kun jij je gang gaan @Manduro!
