### ISSUE TITLE
Refactor Commissievoorkeuren

### ISSUE THREAD

**Issue by qurben** [csrdelft/csrdelft.nl#265]
In 2012 gebouwd en hard aan vervanging toe

**Comment by qurben** [comment]
> Maak het mogelijk om een volgorde aan te geven van de commissies. 
> Am. Praeses

Misschien ook onderscheid maken tussen externe en interne commissies. Of of nog meer categorien maken (BCie, etc)

**Comment by qurben** [comment]
Am. P wil ook graag onderscheid kunnen maken tussen verschillende soorten commissies.

**Comment by mathcals** [comment]
De praeses moet commissievoorkeuren toe kunnen voegen
