### ISSUE TITLE
BB code: afbeelding in link

### ISSUE THREAD

**Issue by Manduro** [csrdelft/csrdelft.nl#27]
Bij gebruik van de volgende BB code wordt er bij klikken op de afbeelding doorgelinkt naar de afbeelding url in plaats van die van de link. Oftewel: een link maken van een afbeelding werkt op dit moment niet.

```
[url=https://csrdelft.nl/]
  [img]https://csrdelft/plaetje.jpg[/img]
[/url]
```

**Comment by brussee** [comment]
Dit zit 'm dacht ik in de forum/javascript functie die een link maakt van een plaatje dat te groot is voor op het forum, maar dat in de praktijk voor elk plaatje doet.
