### ISSUE TITLE
Modulairiseren van de broncode

### ISSUE THREAD

**Issue by qurben** [csrdelft/csrdelft.nl#271]
Misschien is het een goed idee om de source op te splitsen in losse modules (eetplan, mededelingen, bar, bieb, courant, api, peilingen, etc.). Dan krijg je dus
```lib/
  common|gedeeld|gemeenschappelijk|gewoon/
    controller/
    model/
    view/
  eetplan/
    controller/
    model/
    view/
  mededelingen/
    controller/
    model/
    view/
...
```
Dit decoupled de code ook, dan kan je namelijk een beetje in de gaten houden waar je module eindigt.

Op dit moment ben je veel bezig met scrollen als je van een model de bijbehorende views wil hebben.

**Comment by brussee** [comment]
De MVC mappen zijn gemaakt om dit pattern te forceren, toen de code nog in module-mappen stond was het makkelijker om er een zooitje van te maken.

**Comment by qurben** [comment]
Ah, dat is wel een goeie. Ik merk nu alleen dat het best wel zoeken is af en toe als je tussen verschillende onderdelen in een 'module' wil switchen. Maar een beginnende stek dev wil je natuurlijk het liefst de regels laten volgen.

Er moet dus wel iets blijven om ervoor te zorgen dat het zootje maken lastig is.

**Comment by qurben** [comment]
Symfony adviseert hier tegen, je moet geen bundles maken die niet herbruikbaar zijn
