### ISSUE TITLE
Responsive stek

### ISSUE THREAD

**Issue by qurben** [csrdelft/csrdelft.nl#272]
Maak het interne gedeelte van de stek responsief, op dit moment is er een mobiele stek die weinig kan en is de normale layout niet geschikt voor mobiel.

**Comment by brussee** [comment]
De mobiele stek is de gewone stek zonder zijbalk en plat menu.
Normale layout heeft Bootstrap v3.3.4 en de interne frontpage is daarmee responsive gemaakt.

**Comment by qurben** [comment]
Ik zou het zelf nice vinden als de hele interne stek goed mobiel te bezoeken is zonder dat je de pauper stek moet gebruiken (die ik zelf niet fijn vind).

Je ziet ook steeds minder sites die expliciet verschillende sites hebben voor mobiel en desktop, vaak is dit responsieve css die de site mobiel geschikt maakt.

**Comment by brussee** [comment]
Helemaal mee eens. Als de nieuwe back end API af is kan je een hip front end framework pakken en een nieuwe toffe GUI maken. Dat kun je evt. ook per module doen wat mij betreft.

**Comment by qurben** [comment]
Relevant: #3, #74

**Comment by qurben** [comment]
Onlangs gefixt. Verdere verbeteringen worden nog toegevoegd.
