### ISSUE TITLE
BB code parsen voor app

### ISSUE THREAD

**Issue by qurben** [csrdelft/csrdelft.nl#287]
Kijk naar het parsen van bbcode, speciaal voor de app. Op sommige plekken wil de app speciale dingen doorkrijgen. Het liefst gebruiken we de parser die we al hebben hiervoor, omdat deze al allerlei gekke quirks heeft.

Er is al `/htdocs/tools/bbcode.php` die de preview voor het forum fixt, dit hoeft maar een klein beetje uitgebreid te worden.

**Comment by qurben** [comment]
Het beste zou denk ik zijn om een endpoint in de API te exposen die bbcode parsed.

Sub-issue hiervan is om `bbcode.php` te refactoren naar een controller om in de juiste structuur terecht te komen.

**Comment by Manduro** [comment]
In eerste instantie is er geen endpoint nodig, omdat alles nu nog readonly is en er dus geen preview nodig is.

De uitdaging is vooral om te zorgen dat de app met alle verwerkte bb code overweg kan. Er rollen nu allerlei mega complexe views met inline javascript uit. Dat kan ik niet allemaal ondersteunen. Het meeste kan gewoon een link worden naar een url (van de stek of bijv. youtube) ipv een embedded view van een groep of een videospeler.

Een idee is bijvoorbeeld om een soort `class CsrBBSimple extends CsrBB` te maken die waar nodig tags override met een simpele implementatie. Maar deels zullen die functies dan wel dezelfde code bevatten, wat ook niet ideaal is. 

Ander idee is de parser een `$simple_mode` property geven (beetje als de `$email_mode`), met ifs in de tag functies die de simpele versie returnen. Dan worden de bb classes wel nog een stukje groter en ingewikkelder.
