### ISSUE TITLE
Error bij wachtwoord reset

### ISSUE THREAD

**Issue by Manduro** [csrdelft/csrdelft.nl#290]
Als ik lokaal een nieuw wachtwoord probeer in te stellen krijg ik de volgende foutmelding:

```
Fatal error: Call to undefined function CsrDelft\model\security\mhash_keygen_s2k() in /Users/job/Git/csrdelft/lib/model/security/AccountModel.class.php on line 98

Notice: Undefined property: CsrDelft\model\entity\DebugLogEntry::$referer in /Users/job/Git/csrdelft/vendor/csrdelft/orm/src/Entity/PersistentEntity.php on line 149
```
https://github.com/csrdelft/csrdelft.nl/blob/master/lib/model/security/AccountModel.class.php#L98

Op de live stek gaat het wel goed. Kan dit een bug in de autoload refactor zijn, of gaat er misschien iets mis met mijn php installatie? Als ik het goed heb zit de functie standaard in php sinds 5.3.

**Comment by qurben** [comment]
Ik heb er een `\` voor gezet, dit zou laden uit global scope moeten enforcen. De autoloader van php werkt niet altijd even goed met (sommige) functies uit de global scope.

**Comment by Manduro** [comment]
@qurben Hmm, het werkt nu ook niet. Ik lees wat tegenstrijdige informatie over die functie. Voor 5.3 zat hij in een mhash extensie, sinds 5.3 is hij vervangen door de hash extensie die standaard in php zit ([source](http://php.net/manual/en/mhash.installation.php)). Ik draai 5.6.30. Wat draai jij lokaal of wat draait de server bijv.?

```
Fatal error: Call to undefined function mhash_keygen_s2k() in /Users/job/Git/csrdelft/lib/model/security/AccountModel.class.php on line 98

Notice: Undefined property: CsrDelft\model\entity\DebugLogEntry::$referer in /Users/job/Git/csrdelft/vendor/csrdelft/orm/src/Entity/PersistentEntity.php on line 149
```

**Comment by Manduro** [comment]
Oké er is dus nog wel een extensie nodig. Gelukt.

**Comment by qurben** [comment]
😂
