### ISSUE TITLE
Kijken naar js en css laden

### ISSUE THREAD

**Issue by qurben** [csrdelft/csrdelft.nl#3]
Op dit moment halen `css.php` en `js.php` veel code uit DokuWiki. Dit zorgt voor een bak met overhead en zorgt voor meer coupling tussen de stek en de wiki, dit is niet gewild.
# Javascript
- Compress
- Cache
# CSS
- LESS
- Cache

**Comment by qurben** [comment]
Zie ook `lib/view/CompressedLayout.class.php`

**Comment by qurben** [comment]
Waarschijnlijk de CsrMemcache gebruiken, dan wel een cache fixen die op windows werkt voor de devs. Anders wordt de boel waarschijnlijk echt heel erg traag.

Andere optie is de filesystem cache naar een dependency trekken.

**Comment by thervh70** [comment]
@qurben is met het omvormen van de wiki naar submodule al een boel coupling verdwenen? Of zie ik dat verkeerd?
