### ISSUE TITLE
Update google api naar 2.0

### ISSUE THREAD

**Issue by qurben** [csrdelft/csrdelft.nl#30]
Alle googlesync stuff updaten naar de laatste versie in packagist.

https://packagist.org/packages/google/apiclient#v2.0.1

**Comment by brussee** [comment]
Deze kan gesloten worden sinds #36 is ge-merged en al helemaal sinds 31a04b0143d82b4c91d07644bac14cf605263007

**Comment by brussee** [comment]
@qurben ^

**Comment by qurben** [comment]
Sterk punt
