### ISSUE TITLE
Smarty Instellingen plugin

### ISSUE THREAD

**Issue by Erackron** [csrdelft/csrdelft.nl#311]
Een Smarty plugin die een instelling ophaalt, in stijl van de toegang plugin.

**Comment by qurben** [comment]
Nice. We moeten hier alleen niet te hard in doordraven. Veel logica die in de view zit hoort er niet in thuis en moet eruit gerefactored worden.

**Comment by qurben** [comment]
Smarty is deprecated geworden. In Blade is het aanroepen van PHP iets duidelijker en beter ondersteund (je kan in PHPstorm gewoon doorklikken en usages worden gevonden)
