### ISSUE TITLE
Plaetjes uploaden via het forum

### ISSUE THREAD

**Issue by qurben** [csrdelft/csrdelft.nl#337]
Maak het mogelijk om willekeurige plaetjes (die dus niet in een fotoalbum passen) op de stek te zetten in een forum draadje. Zoals Github/Gitlab het doen lijkt me wel mooi.

Op deze manier houdt je de controle over afbeeldingen die op de stek gezet worden en is het makkelijker om dit allemaal intern te houden.

Er moet een soort van mechanisme ingebouwd worden waarbij ongebruikte plaetjes automatisch verwijderd worden, zodat iemand die een paar keer gefaelt heeft met een plaetje online zetten geen waardevolle MB's voor niets gebruikt.

Misschien ook wel jeuk om voor externen aan te zetten, maar dan moet er wel nog meer beveiliging aan gehangen worden. (identificeren op uuid, goede rate limit enzo)

**Comment by mathcals** [comment]
Schop. Dit is nog steeds een goed idee.

**Comment by qurben** [comment]
🎉
