### ISSUE TITLE
Zelfstandig wachtwoord aanvragen werkt niet

### ISSUE THREAD

**Issue by thervh70** [csrdelft/csrdelft.nl#341]
De wachtwoord aanvragen tool is stuk!
In de mailbox staan een hoop mails met mensen die klagen.

Ze krijgen mail om hun wachtwoord te vervangen en die stuurt ze naar een pagina waar wordt gevraagd je wachtwoord te vervangen en daarvoor je mail in te vullen (of iets dergelijks) er zit een soort van infinite loop in.

**Comment by qurben** [comment]
gereproduceerd

**Comment by qurben** [comment]
Gefixt en teruggemaild
