### ISSUE TITLE
Digitale declaraties

### ISSUE THREAD

**Issue by thervh70** [csrdelft/csrdelft.nl#345]
Mogelijkheid voor leden om digitale decla's in te vullen

### Formulier
Deze is voor leden die decla's invullen
- [x] Algemene gegevens invullen (datum van aankoop, commissie waarvoor deze geldt, opmerkingen etc.)
- [x] Automagisch aanvullen met rekeningnummer van lid (keuze stekrekeningnummer of ander nummer misschien)
- [x] Per bedrag BTW schaal aangeven, die vervolgens door stek laten berekenen (let op afronding!)
- [x] Automagisch gegevens lid invullen
- [x] Automagisch datum van invullen toevoegen
- [x] Goedkeuroverzicht voor versturen (dit is onomkeerbaar neem ik aan)
- [x] Calculator voor BTW bedragen in formulier
- [x] Bon uploaden (foto of pdf, zou episch zijn als dit via mobiel kon en dus asynchroon met invullen formulier als dat via PC wordt ingevuld)

### Overzicht
- [x] Fiscus overzicht met alle stek decla's (alles exact commissies)
- [x] Commissie fiscus overzicht waarin hij/zij declanummer, etc. kunnen invullen
- [x] PDF genereren op basis van formulier
- [x] Formulier aanpassen alvorens PDF bouwen (deze maakt mooi decla overzicht op 1 A4 en plakt de bon erachter)

**Comment by FrostMegaByte** [comment]
Deze issue is best wel van grote prioriteit na het gesprek met het bestuur van laatst. De omschrijving was als volgt:
- Declaraties uploaden op de stek zodat Amy die makkelijk kan verwerken. Het moet in een PDF komen, want ze moeten naar Exact geupload kunnen worden.

Alles wat in deze issue beschrijving staat is dus wel relevant

**Comment by qurben** [comment]
Ook even kijken of de uitvoer van dit ook naar xml voor exact kan.

**Comment by jptned** [comment]
Vier jaar later, maar alle features die je bedacht had zijn geïmplementeerd, @thervh70 😄
