### ISSUE TITLE
Sponsorkliks Chrome extensie

### ISSUE THREAD

**Issue by thervh70** [csrdelft/csrdelft.nl#348]
AcqCie wil een chrome extension die alle verkeer naar webwinkels via de sponsorkliks stuurt.
Geniaal idee, wel even kijken of dit gemaakt kan worden.

**Comment by qurben** [comment]
Redirect een site via sponsorkliks 
Scrapen van sponsorkliks

**Comment by qurben** [comment]
We gaan hiermee verder in https://github.com/csrdelft/sponsorkliks
