### ISSUE TITLE
Logboek van groep is stuk

### ISSUE THREAD

**Issue by qurben** [csrdelft/csrdelft.nl#349]
# stappen om te reproduceren

* Ga naar https://csrdelft.nl/groepen/commissies/beheren
* Selecteer een commissie
* Klik op de knop **Logboek**

# Wat er gebeurt

* Alert met html erin
* Error op Slack

# Wat er moet gebeuren

* Modal met logboek erin moet weergegeven worden.

**Comment by thervh70** [comment]
Hoe vaak wordt dit gebruikt? Hoe lang is het al stuk?

Lijkt me dat we dit er ook gewoon uit kunnen slopen 🔨

**Comment by qurben** [comment]
Gefixt in aafd71019d2401e24deebb72a76b61c256fe1f3c
