### ISSUE TITLE
Mededelingen zijn niet volledig leesbaar

### ISSUE THREAD

**Issue by Boudewijn26** [csrdelft/csrdelft.nl#353]
https://csrdelft.nl/mededelingen/747
![image](https://user-images.githubusercontent.com/2896917/33278153-eeb1aa1c-d39a-11e7-8e5b-38d6805e56f7.png)

Ik kan het bericht niet lezen...

**Comment by qurben** [comment]
Dat klopt, deze mededeling is ingesteld op alleen zichtbaar voor leden. In de zijbalk klopten de lijst niet helemaal, waardoor je meer kon zien dan de bedoeling was. Dit is nu gefixt.

**Comment by qurben** [comment]
(Mededelingen is nog steeds een zooi, helaas)
