### ISSUE TITLE
Uitgebreidere router

### ISSUE THREAD

**Issue by qurben** [csrdelft/csrdelft.nl#37]
# Huidige staat

Er is een `.htaccess` bestand die de juiste controller aanroept, iedere controller heeft z'n eigen manier van routes afhandelen. De huidige manier is erg krachtig, maar soms is het een beetje onoverzichtelijk wat er nou precies gebeurt.
# Ideale staat

Een PHP router die op basis van reguliere expressies de juiste controller & functie kan vinden en hier de juiste actie kan uitvoeren. Eventueel met reverse routing. Misschien kan de ACL al worden gecheckt in de router.

**Comment by brussee** [comment]
Meer complexiteit toevoegen is ongewenst in verband met mogelijke gaten in de beveiliging of veiligheid van routeren. Als je het verbeterd maak het dan vooral simpeler en minder fancy, maar degelijk.

**Comment by brussee** [comment]
From: https://nikic.github.io/2014/02/18/Fast-request-routing-using-regular-expressions.html
> There are a few technical takeaways from this post: The combined regex approach works great for a small number of regular expressions, but is suboptimal if many regular expressions are involved and disastrous if there are many capturing groups per rule.

**Comment by qurben** [comment]
Gerelateerd aan #184.

Een router die volledig in PHP leeft heeft denk ik best wel veel voordelen. Zoals dus #184, maar ook een kans om routes nog iets meer consistent te trekken (ook al is de huidige staat niet heel slecht).

Ingewikkelde dingen met reguliere expressies zijn denk ik niet nodig.

Een systeem met placeholders lijkt me wel heel erg mooi. Bijvoorbeeld dat je de route `/groepen/commissies/{id}/` kan definieren en dat `{id}` wordt doorgegeven aan de functie die de request afhandeld. Op deze manier kun je beter inzicht krijgen in welke routes er precies zijn.

Verder denk ik dat zoals we nu controllers selecteren best wel goed is, het kan misschien nog wat strenger. Dus dat alle urls die beginnen met `/groepen/` strikt worden afgehandeld door de `GroepenController` en dat dan ook `/groepen-en-dingen/` kan worden afgehandeld door de `GroepenEnDingenController`.

**Comment by mathcals** [comment]
Als we nog naar Laravel willen dan zit het daar natuurlijk ook in, maar ik weet niet of dat nog in de planning zit

**Comment by qurben** [comment]
Gefixt in #537 met de Symfony router.
