### ISSUE TITLE
Verfijn toegangsrechten fotoalbums

### ISSUE THREAD

**Issue by mathcals** [csrdelft/csrdelft.nl#370]
Momenteel kunnen fotoalbums privé worden gemaakt door '(intern)' in de titel te zetten. Een betere oplossing zou zijn dit bijvoorbeeld in de database aan te geven. Ook een optie zou zijn om in fotoalbums een mapje public te maken en alleen foto's daarin publiek te maken.

Rechtencontrole gebeurt momenteel bovendien in het FotoalbumModel. Dit hoort in de controller te gebeuren.

**Comment by mathcals** [comment]
Het lijkt mij een goed idee om per foto een boolean public te maken in de database. Misschien ook nog eentje per album. Een foto is dan alleen publiek toegankelijk als zowel de foto zelf als het album waar hij instaat publiek toegankelijk is.

**Comment by qurben** [comment]
Dat lijkt me een goed idee inderdaad. 

Iedereen met rechten `P_ALBUM_MOD` (BASF-Cie, Bestuur, PubCie) mag dit aanpassen. Dit zichtbaar maken voor iedereen, anders vinden mensen het vreemd als sommige albums niet zichtbaar zijn voor externen.

En dan misschien per album aangeven met een icoontje dat ie intern is, zoals hieronder.
![Voorbeeld](https://i.imgur.com/LHiDK7q.png)

Of misschien het omgekeerde maken.
![Voorbeeld](https://i.imgur.com/WXLhPs1.png)

**Comment by qurben** [comment]
Ik neig een beetje naar publieke albums expliciet maken en de boel default intern te maken. Dan worden albums van leden default intern.

**Comment by qurben** [comment]
En dan bij publieke albums een icoontje toevoegen aan de icoontjesbalk of deze publiek is, alleen in publieke albums.

![Voorbeeld](https://i.imgur.com/lnYETMD.png)
![Voorbeeld](https://i.imgur.com/lr5pv6v.png)

**Comment by mathcals** [comment]
Ja, dat lijkt me een goed idee. Misschien slim om dit ook even met de fotocommissarissen te overleggen.

**Comment by mathcals** [comment]
Ik ga hiermee aan de slag

**Comment by qurben** [comment]
Met de implementatie zou je ook een compleet losse versie van het foto album kunnen maken voor de externe stek. Dan hoeft er geen ingewikkelde rechtencode door de fotoalbum code heen te lopen.

**Comment by mathcals** [comment]
Klopt inderdaad Hangt er een beetje van af hoeveel publieke foto's we willen. Als we regelmatig foto's in het publieke album willen plaatsen is het denk ik toch overzichtelijker om één album te hebben waar bepaalde foto's publiek zijn. Anders ga je toch krijgen dat foto's meerdere keren op de stek staan in verschillende albums.

**Comment by qurben** [comment]
Misschien wel goed om even na te vragen wat de fotoco's leuk vinden.
