### ISSUE TITLE
Onderzoek en verwijder overbodige velden in profiel

### ISSUE THREAD

**Issue by qurben** [csrdelft/csrdelft.nl#386]
Hiervoor moet even met de NovCie gepraat worden.

De volgende velden komen o.a. in aanmerking voor verwijdering.

- `kgb`
- `vrienden`
- `middelbareSchool`
- ~`ovkaart`~
- `muziek`
- `zingen`

**Comment by qurben** [comment]
- `studienr`

**Comment by mathcals** [comment]
Volgens mij wordt het veld 'muziek' weleens gebruikt bij de kringindeling. Wat mij betreft plaatsen we die gewoon in het privacybeleid, aangezien dat ook geen gevoelige informatie is

**Comment by mathcals** [comment]
middelbareSchool staat wel in het privacybeleid

**Comment by qurben** [comment]
Vooral ff dubbelchecken, het kan best zijn dat er al jaren niet meer naar 'muziek' gekeken wordt

**Comment by qurben** [comment]
Daarnaast kunnen velden interessant blijven tijdens het novitiaats-halfjaar, en moeten anderen eigenlijk zsm verwijderd worden na de novitiaatsweek
