### ISSUE TITLE
Welkom script gebruiksvriendelijk maken

### ISSUE THREAD

**Issue by qurben** [csrdelft/csrdelft.nl#40]
`bin/welkom.php` moet worden geupdate om het voor een PubCie-P makkelijker te maken om een lichting te verwelkomen op de stek.

Op dit moment is deze pagina ook stuk.

Daarnaast kan `/wachtwoord/vergeten` ook `/wachtwoord/aanvragen` worden. Ziet er direct minder gebeund uit. ~Beter is nog wel om een link naar een pagina te maken die automatisch een wachtwoord stuurt.~ Een link met een reset token erin, waarna de noviet een 'maak wachtwoord aan' prompt krijgt.

**Comment by brussee** [comment]
> een wachtwoord stuurt

*Nooit* wachtwoorden over onbeveiligde verbinding (zoals email) sturen. Alleen reset tokens, die ook confirm via registered email zouden moeten vereisen. Nu alleen melding "iemand heeft je wachtwoord gewijzigd" dacht ik?

**Comment by qurben** [comment]
welkom.php is nu de `stek:welkom` command (9f4a35f96e509158762900ade6251bba6956d3a5). Deze hoeft niet meer ieder jaar veranderd te worden (alleen als de inhoudelijke tekst van de mail veranderd)

Het sturen van een tokenlink zorgt waarschijnlijk voor onveilige en onduidelijke situaties omdat de tokens best lang houdbaar moeten zijn en als een token per ongeluk gebruikt wordt moet de noviet alsnog een nieuwe token aanvragen. Novieten via /wachtwoord/aanvragen sturen lijkt mij een prima oplossing.
