### ISSUE TITLE
FotoCo Rechten

### ISSUE THREAD

**Issue by Dyxl3ct1c** [csrdelft/csrdelft.nl#400]
Een tijdelijke toegang tot Fotorechten voor een Owee-promotiedame

**Comment by mathcals** [comment]
In principe kan dit zodra #399 gefixt is toch?

**Comment by qurben** [comment]
We hebben nog geen specifieke fotorechten.

**Comment by mathcals** [comment]
Oja, dat is #388

**Comment by qurben** [comment]
Inderdaad, duplicate van #388
