### ISSUE TITLE
Inschrijfformulier novieten herzien

### ISSUE THREAD

**Issue by Dyxl3ct1c** [csrdelft/csrdelft.nl#402]
Vakken weghalen waarvan we geen informatie willen verzamelen.

**Comment by qurben** [comment]
Velden OV kaart en studienummer zijn verwijderd (c6b22265d7bd9f9af174ff467f437d0c15e915ba, 8cde420452a8d1120e3e6c577a7a70757a1b07b9).

Toestemmingformulier is toegevoegd (7557101e3ae0d4173670f0c2bc6121370571a92a)
