### ISSUE TITLE
Favoriet toevoegen in menu is stuk

### ISSUE THREAD

**Issue by qurben** [csrdelft/csrdelft.nl#411]
Als je in het algemene menu op 'deze pagina aan favorieten toevoegen' klikt, gebeurt er niets.

**Comment by brussee** [comment]
[url]/forum/onderwerp/10716#ongelezen[/url]

1) Ik ga naar een draadje in het mooiste subforum van de stek.
2) Toen klikte ik op het knopje met de ster (om het draadje toe te voegen aan mijn favorieten, naast de knopjes met de envelop voor het volgen van een forumdraadje per mail en die voor de zijbalk).
3) Er gebeurt niets.

[b]Status: open[/b]


edit: Dezelfde functionaliteit via het hoofdmenu (favoriet toevoegen) is ook stuk en laat het menu vastlopen op mijn slimpauper.
