### ISSUE TITLE
Weergaveproblemen bij ketzers met veel parallelle keuzes

### ISSUE THREAD

**Issue by Dyxl3ct1c** [csrdelft/csrdelft.nl#434]
Mensen kunnen zich niet aanmelden voor een werkgroep, omdat er tekst voor de aanmeld-button verschijnt

**Comment by Erackron** [comment]
Heeft te maken met de hoeveelheid paralelle keuzes in de ketzer.
Navigeren met het toetsenbord is mogelijk om het probleem momenteel te omzeilen.

**Comment by qurben** [comment]
Gefixt in #435, verbeterd in 54b8800b7f3e0a059195366a15b8ffc3d61fa8b2
