### ISSUE TITLE
Subforum dropdown onleesbaar

### ISSUE THREAD

**Issue by qurben** [csrdelft/csrdelft.nl#443]
De titel 'Openbaar' is wit op licht-grijs.

![](https://i.imgur.com/wfW0tP9.png)

**Comment by FrostMegaByte** [comment]
![fixed extern](https://user-images.githubusercontent.com/24373899/48497160-e3586f80-e833-11e8-9801-0d1785a47ae4.png)

Dit is hoe ik het voor nu gefixt heb
