### ISSUE TITLE
Extern forum RSS waarschuwt dat de link geheim moet blijven

### ISSUE THREAD

**Issue by qurben** [csrdelft/csrdelft.nl#444]
De url is https://csrdelft.nl/forum/rss/csrdelft.xml, de externe rss heeft geen token dus hier is deze waarschuwing overbodig.

![](https://i.imgur.com/hmUXV6u.png)

**Comment by qurben** [comment]
De uitlijning van dit icoon is ook een beetje meh.

**Comment by CodexNine** [comment]
Is dit nog steeds een probleem? Ik kan op de meest recente branch geen RSS-icoon vinden op het externe forum.

**Comment by qurben** [comment]
Is vervangen door een favicon icoontje, de hover over het prive houden bestaat nog, maar zie je niet als je over de icon of de textbox hovert. wel als je daarnaast hovert.

**Comment by jobvonck** [comment]
Ik kan deze link niet meer vinden op het externe forum, dus ik vermoed dat het probleem al is verholpen door het te verwijderen.
