### ISSUE TITLE
Onhover externe stek heeft problemen

### ISSUE THREAD

**Issue by qurben** [csrdelft/csrdelft.nl#445]
![](https://i.imgur.com/HA4kUGS.png)

De onhover op de externe stek laat ook de hover tekst helemaal links onderin de pagina zien. Dit is helemaal nergens voor nodig.

En de tekst valt buiten het ding.

**Comment by qurben** [comment]
`extern.css` mist de style van `ui-helper-hidden-accessible` uit jquery-ui core, deze moet eigenlijk wel geladen worden.

```scss
@import "~jquery-ui/themes/base/core.css";
```

Verder heeft de `ui-tooltip` klasse in extern `whitespace: nowrap`, dit is niet wat we willen hier. Weet niet hoe dit er is ingeslopen.

**Comment by M2WZ** [comment]
Is met de nieuwe stek-layout gefixt (door gwn helemaal uit te commenten), dus ik sluit nu de issue.
