### ISSUE TITLE
Create fixtures

### ISSUE THREAD

**Issue by qurben** [csrdelft/csrdelft.nl#45]
Create a dataset without user data, for developers

**Comment by qurben** [comment]
Op deze manier wordt het laagdrempeliger om voor de stek te developen en is het makkelijker om gast-devs te hebben die we liever niet de hele stek database geven.

**Comment by Manduro** [comment]
Ja sowieso doen! Het is op dit moment niet bepaald laagdrempelig om te developen. Liefst wil je alleen hoeven clonen en verder wat gedocumenteerde cli commando's uitvoeren zonder na te hoeven denken. Dan kost het een minuut ipv een dag.

**Comment by brussee** [comment]
Dit was er: https://trac.knorrie.org/csrdelft.nl/wiki/SnelStartHandleiding

> !!! database aanpassing ook als xxxx_omschrijving.sql mee committen xxxx is commit nummer waar t bij hoort. Zie voor voorbeelden op ​https://trac.knorrie.org/csrdelft.nl/browser/trunk/sql

**Comment by thervh70** [comment]
Schopperdeschop @qurben
