### ISSUE TITLE
Error wanneer net uitgelogd

### ISSUE THREAD

**Issue by qurben** [csrdelft/csrdelft.nl#46]
![](http://i.imgur.com/rI1tCVK.png)

Dit is op Syrinx

**Comment by brussee** [comment]
Die melding zit in je $_SESSION dus kan soms lang blijven hangen. Komt het nog steeds voor?

**Comment by qurben** [comment]
Ik heb geen tijd gehad om hier dieper op in te gaan, ik kreeg een error die in productie niet voor mag komen.
