### ISSUE TITLE
Dark Mode thema

### ISSUE THREAD

**Issue by qurben** [csrdelft/csrdelft.nl#477]
Zie ook https://csrdelft.nl/forum/onderwerp/10963

**Comment by FrostMegaByte** [comment]
Oeeeh, dit lijkt mij leuk om te maken!

**Comment by qurben** [comment]
Zie ook de thema's pagina op de github wiki

**Comment by qurben** [comment]
Pas geleden heb ik het thema maken wat omgegooid, zodat het minder een gevogel is met specifieke details. Dus het wordt meer iets van

```
$black: #fff;
$white: #000;
```

**Comment by FrostMegaByte** [comment]
![Kleine preview](https://user-images.githubusercontent.com/24373899/51088018-097a8d00-175b-11e9-8765-57fa81eecb05.png)

**Comment by mathcals** [comment]
Met mediaqueries kun je ook dark mode via de browser detecteren en dan automatisch ook de stek in dark mode zetten. Zit overigens alleen nog maar in de Preview Release van safari en nog niet in de definitieve versie.
