### ISSUE TITLE
Presentielijst tool voor de HV

### ISSUE THREAD

**Issue by FrostMegaByte** [csrdelft/csrdelft.nl#512]
Hey bestuur gaf bij een meeting met Job en Mark aan graag een presentielijst tool te willen hebben voor HVs.
De bijschrijving die ze gaven was:
- presentielijst tool voor de HV (bij lidstatus verandering naar andere kolom)

Momenteel gebeurd namelijk alles met een word document en dat kan dus beter. Wil je hier meer over weten, contacteer dan de vice-abactis

**Comment by qurben** [comment]
Beter samen voegen met #167
