### ISSUE TITLE
Agenda importeren zonder verjaardagen, maar verjaardagen nog wel in de agenda op de stek

### ISSUE THREAD

**Issue by FrostMegaByte** [csrdelft/csrdelft.nl#513]
Momenteel kan je namelijk de agenda prima importeren zonder verjaardagen, maar dan moeten de verjaardagen ook uit blijven staan in de instellingen op de stek. Als je de verjaardagen weer aanzet om weer te geven, dan update de geimporteerde agenda weer en staan alle verjaardagen erbij.

**Dus simpelweg, agenda kunnen importeren zonder verjaardagen, maar dat verjaardagen nog wel in de agenda op de stek aan kunnen blijven.**

**Comment by qurben** [comment]
Oftewel nog een extra knopje maken onder 'Toon verjaardagen in agenda'
