### ISSUE TITLE
Corveebeheer geen werkende automatisch suggesties en 2 knoppen met omgekeerde functie

### ISSUE THREAD

**Issue by FrostMegaByte** [csrdelft/csrdelft.nl#514]
Er kwam een mailtje binnen van de CorveeCaesar met het volgende bericht:

"Als ik op de pagina 'corveebeheer' een corveetaak wil toewijzen door op het poppetje bij de betreffende taak te klikken en dan een lid te selecteren gaat er een aantal dingen niet zoals het hoort:
1. als ik op een poppetje heb geklikt kan ik in het menuutje dat verschijnt zoeken op naam of lidnummer. Dat is heel handig, vooral als deze zoekfunctie automatisch suggesties doet zoals ook gebeurt bij zoeken over de hele stek. Maar die suggesties worden sinds een tijdje niet meer gegeven, waardoor ik of de hele naam moet intikken of het lidnummer op moet zoeken. Het zou chill zijn als die suggesties weer terug konden komen.
2. in hetzelfde menuutje zitten 2 checkboxes: 'met voorkeur' en 'niet recent gecorveed'. Normaal gesproken zouden, als ik bijvoorbeeld 'met voorkeur' heb aangevinkt, in het menuutje alleen leden blijven staan die hun voorkeur hebben aangegeven voor de betreffende corveetaak en als ik 'met voorkeur' niet heb aangevinkt blijven alle leden in het menuutje staan. Maar sinds een tijdje hebben beide checkboxes een precies omgekeerde werking, wat op zich geen groot probleem is, maar wel een beetje raar dus het zou chill zijn als ze weer zouden kloppen."

P.S.: Volgens mij gingen beide puntjes ongeveer rond dezelfde tijd voor het eerst fout.

**Comment by FrostMegaByte** [comment]
Ik heb voor nu @jptned hierop gezet, want hij heeft laatst gewerkt aan automatische suggesties op de stek en zal dit dus wss vrij vlot kunnen vinden. Maar op zich kan iedereen hier wel aan werken als je een oplossing weet.

**Comment by jptned** [comment]
Ik denk niet dat het te maken heeft met mijn dingen met naamsuggesties, maar ga hier zo eens induiken.
