### ISSUE TITLE
Repareer edge cases pasfotos

### ISSUE THREAD

**Issue by qurben** [csrdelft/csrdelft.nl#521]
- Er zit iets in pasfotos zodat de naamweergave kan beinvloeden waar de profielfoto vandaan worden gehaald, dit werd gebruikt voor duckstad fotos. Dit is stuk
- Als er geen foto kan worden gevonden, wordt er in `Profiel::getPasfotoPath` naar `/plaetjes/pasfoto/geen-foto.png` verwezen, dit werkt niet.

**Comment by FrostMegaByte** [comment]
Was dit al gefixt? Ik checkte net via iemands profiel en het lijkt op zich iets te doen, dus was benieuwd

**Comment by qurben** [comment]
Normale case werkt. Duckstadfoto's werken niet (misschien eruit slopen). En geen foto verwijst niet helemaal naar de goede plek, werkt wel.

**Comment by qurben** [comment]
Dit is ondertussen gerepareerd volgens mij.
