### ISSUE TITLE
Commissie voorkeuren, link automatisch lidnummer invullen

### ISSUE THREAD

**Issue by FrostMegaByte** [csrdelft/csrdelft.nl#534]
# Wat houdt het in?
**Link:** https://csrdelft.nl/profiel/[LIDNUMMER]/voorkeuren
Dat bij [LIDNUMMER] automatisch je lidnummer wordt ingevuld als je al bent ingelogd in de stek

**Comment by FrostMegaByte** [comment]
Top! Werkt dit nu door gewoon naar https://csrdelft.nl/profiel/voorkeuren te gaan?

**Comment by jptned** [comment]
Jep! Net uitgerold. https://csrdelft.nl/profiel/voorkeuren verwijst nu door naar http://csrdelft.nl/profiel/[lidnummer]/voorkeuren. Hetzelfde gelijk voor https://csrdelft.nl/profiel/bewerken gedaan
