### ISSUE TITLE
Maak php log tool

### ISSUE THREAD

**Issue by mathcals** [csrdelft/csrdelft.nl#545]
Zorg ervoor dat errors overzichtelijk gelogd worden (bijvoorbeeld opgeteld per bestand)

**Comment by qurben** [comment]
We kunnen naar https://sentry.io kijken.

**Comment by mathcals** [comment]
Ja dat ziet er heel nice uit. Alleen jammer dat de gratis versie maar één gebruiker ondersteunt

**Comment by qurben** [comment]
We kunnen eventueel een ding hebben met een account waar we allemaal op zitten, maar is inderdaad niet optimaal.

**Comment by qurben** [comment]
https://github.com/errbit/errbit

**Comment by qurben** [comment]
Je kan Sentry ook self hosted krijgen https://github.com/getsentry/sentry

Voor een self-hosted oplossing moeten we even kijken wat de mogelijkheden zouden zijn, want de meesten draaien niet op PHP.

**Comment by mathcals** [comment]
Ja dat zag ik. Sentry draait op python volgens mij en is misschien een beetje overkill. Errbit zag er ook goed uit en is denk ik wat simpeler, maar doet volgens mij wel precies wat we willen. Die draait op Ruby volgens mij, dus ik weet ook niet in hoeverre we die kunnen gebruiken.

**Comment by qurben** [comment]
We zouden kunnen kijken of er budget is om ergens een vps neer te zetten.

Daarnaast kunnen we ook zelf een tool bouwen die dit doet, zo groot zijn onze eisen ook weer niet. Gewoon alle errors wegschrijven naar een file en dan een view bouwen op die files.

**Comment by mathcals** [comment]
Een vps voor dit doel lijkt me een beetje overdreven. Wat we willen is inderdaad ook weer niet zo ingewikkeld. Zelf heb ik maandag https://github.com/amnuts/phperror-gui een beetje geprobeerd (die parset gewoon de php error log file). Heel erg simpele tool, maar volgens mij niet heel overzichtelijk.

**Comment by qurben** [comment]
sentry werkt goed.
