### ISSUE TITLE
foto's werken niet op voorpagina

### ISSUE THREAD

**Issue by Klap-in** [csrdelft/csrdelft.nl#558]
Ik was niet ingelogd, en dan staan er onder kopje Foto's alleen linkjes (zoals: https://csrdelft.nl/plaetjes/fotoalbum/Publiek/Voorpagina/pic03.jpg)

https://csrdelft.nl/#four

**Comment by mathcals** [comment]
De foto's lijken te zijn verwijderd uit het publieke fotoalbum

**Comment by qurben** [comment]
Oeps, over het hoofd gezien bij #556
