### ISSUE TITLE
Foutmeldingen googlesync

### ISSUE THREAD

**Issue by mathcals** [csrdelft/csrdelft.nl#559]

**Comment by qurben** [comment]
Foutmelding
```
Error parsing xml. Content was: {
  "error": {
    "code": 403,
    "message": "The caller does not have permission",
    "status": ...
```
• Moment Tue, 24 Sep 2019 17:56:45 +0200
• Type Onbekende fout 0
• Bestand /srv/www/csrdelft.nl/lib/common/GoogleSync.php
• Regel 706

**Comment by mathcals** [comment]
Mogelijk een verlopen of ingetrokken access token voor de google API? Na het ontvangen van dit soort foutmeldingen verwijdert de stek volgens mij ook de token, maar de afhandeling is nog niet helemaal goed. Eigenlijk moet de stek deze json response parsen om te kijken welke error er terug wordt gegeven.

**Comment by qurben** [comment]
Ja waarschijnlijk, maar deze case moet inderdaad gewoon netjes afgehandeld worden.

**Comment by qurben** [comment]
Relevant: #605

**Comment by qurben** [comment]
De huidige implementatie van GoogleSync is kaput (door #605) en moet dus sowieso herschreven worden.
