### ISSUE TITLE
Ical export voor losse agenda events.

### ISSUE THREAD

**Issue by qurben** [csrdelft/csrdelft.nl#565]

**Comment by qurben** [comment]
Werkt nog matig, hopelijk na c0ce3e695 ietsje beter.

**Comment by qurben** [comment]
Ik heb zelf geen hele goede use-case hier voor, want ik gebruik alleen Google Calendar en die werkt maar half met .ics bestanden. Ik krijg m op mobiel uberhaupt niet zo gek dat ie .ics gaat happen. Het kan zijn dat ik hier nog iets mis.

Voor outlook werkt het op zich wel prima.

**Comment by brussee** [comment]
Google Calendar weigert te importeren inderdaad, terwijl een random ical validator zegt dat het in orde is en de Windows 10 mail client 'm wel pakt.

**Comment by qurben** [comment]
Google Calendar als import via de desktop website hapt m bij mij wel, maar dat is wel omslachtig. De app gaat niet akkoord, maar dat gebeurde bij mij ook bij een ical gegenereerd van een website op het internet.
