### ISSUE TITLE
Inketzen in overige groepen werkt niet

### ISSUE THREAD

**Issue by jptned** [csrdelft/csrdelft.nl#589]

**Comment by jptned** [comment]
Onderdeel van #590

**Comment by FrostMegaByte** [comment]
Ziet er naar uit dat dit nog niet is behandeld in #590.
Moet dus nog verder naar gekeken worden.

**Comment by qurben** [comment]
Onderdeel van #590 is ook niet op z'n plek eigenlijk, het was vooral 'on hold door #590'.

**Comment by qurben** [comment]
Waarom prio:high? Dit is al vet lang stuk toch?

**Comment by FrostMegaByte** [comment]
Bestuur wil dit jaar graag de mogelijkheid voor bidgroepen hebben en we zeiden op de vorige vergadering dat we deze overige groepen wel konden gebruiken om een nieuwe groep aan te maken waar mensen dan in kunnen ketzen om aan te geven dat ze een bidgroep willen.

Wellicht niet helemaal correct dat het "inketzen in een overige groep" toepasbaar is voor deze bidgroepen. Maar later wil je alsnog dat mensen zich in deze overige groep kunnen inketzen, dus moet wel gefixt zijn.

prio:high is dus voornamelijk vanwege het bidgroepenpuntje van het bestuur dit jaar

**Comment by qurben** [comment]
Kunnen we een label 'bestuursbeleidpuntje' maken?

**Comment by qurben** [comment]
Er zijn op dit moment een hele boel groepen die als aanmeldrechten `P_LOGGED_IN` hebben. Deze groepen moeten wel even dicht gezet worden, want bij veel van deze groepen is het niet de bedoeling dat er nog mensen aan toegevoegd worden.

**Comment by qurben** [comment]
Ik ben er even door heen gegaan, alle oude groepen die niet meer relevant zijn hebben nu `P_LEDEN_MOD` als aanmeldrechten.
