### ISSUE TITLE
Trac Wiki migreren naar Stek Wiki

### ISSUE THREAD

**Issue by brussee** [csrdelft/csrdelft.nl#60]
In de Trac Wiki heeft oud-PubCie hoop tijd in gestoken voor o.a. overdracht developers. Zie bijv. https://trac.knorrie.org/csrdelft.nl/wiki/permissies

Migreren naar Stek Wiki is beter dan naar GitHub, want je wilt alles op 1 plek en geen versplintering.

**Comment by qurben** [comment]
Ik denk dat het goed is om implementatiedetails, zoals werking van het Framework bij de code te bewaren. Alle dingen die specifiek zijn aan de PubCie, het modereren of gebruiken van de stek moeten inderdaad op de stek wiki.

**Comment by brussee** [comment]
Inderdaad.

Hier nog meer ideeën over de toekomst van de Wiki: https://csrdelft.nl/forum/onderwerp/8573/1

**Comment by brussee** [comment]
Het zou heel fijn zijn om het kip-ei-verhaal te doorbreken:

"Ik kom nooit op de Wiki"

"Ik heb geen zin iets op de Wiki te zetten, want niemand (dwz ik) leest dat."

**Comment by qurben** [comment]
Trac wiki bestaat niet meer.
