### ISSUE TITLE
Versimpelen van de wachtwoordprocedure

### ISSUE THREAD

**Issue by FrostMegaByte** [csrdelft/csrdelft.nl#601]
Wachtwoord moet momenteel aan heel veel eisen voldoen.
Dit moet eigenlijk versimpeld worden.

Dit helpt:
- Oudleden
- Mensen die hun wachtwoord moeten resetten

**Comment by FrostMegaByte** [comment]
Graag voor het eind van 2019 klaar hebben. Dit is wat ik aan Jan-Bart had verteld en lijkt mij wel te doen  qua tijd

**Comment by mathcals** [comment]
Oké. Misschien goed om even te bedenken wat we precies willen dan. 
Dit zijn mogelijke oplossingen:

- Wachtwoord moet niet meer elke 6 maanden verlopen
   - voor oud-leden, voor leden misschien nog wel?
- Versoepelen van de wachtwoordeisen
   - Momenteel moet een wachtwoord langer zijn dan 23 tekens of langer dan 10 en ook hoofdletters, kleine letters, cijfers en speciale tekens bevatten.
   - De vraag is in hoeverre je hiervan eisen moet willen schrappen. Uiteindelijk moeten wachtwoorden wel veilig blijven natuurlijk.
- Wachtwoordreset mogelijk maken met alleen e-mailadres (zonder lidnummer dus)
- Inloggen met e-mailadres mogelijk maken

**Comment by qurben** [comment]
Lidnummer uit de resetflow halen is sowieso een top idee. Dan moet er nog wel iets verzonnen worden voor die paar accounts die hetzelfde mailadres hebben.

**Comment by brussee** [comment]
Wachtwoord-loos inloggen (alleen lidnummer/email adres) is een gebruiksvriendelijke maatregel die je kunt treffen, want qua veiligheid is het hetzelfde als wachtwoord resetten.

Voor de gewone gebruikers met een moderne laptop met Windows Hello: https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/webauthnapis
En voor de nerds onder ons zou het ook heel tof zijn om met je security key te kunnen inloggen (zoals de 2FA bij de grote jongens, google en fb bijv.)

**Comment by qurben** [comment]
Kunnen we deze issue wat concreter maken? Op dit moment is het nogal vaag wat er precies moet gebeuren.

**Comment by jptned** [comment]
Wat er in ieder geval moet komen is een mogelijkheid om in te loggen en wachtwoorden te resetten o.b.v. alleen een e-mailadres.

Verder is dus de overweging wat we doen met verlopende wachtwoorden. Wat mij betreft schrappen we dat volledig (zie ook [dit artikel](https://www.sans.org/security-awareness-training/blog/time-password-expiration-die)), maar weet niet hoe jullie daar over denken?

**Comment by qurben** [comment]
Dan lijkt het me voor deze issue mooi om wachtwoordreset zonder uid te maken en dan twee nieuwe issues maken voor verlopen van wachtwoorden en one-time tokens.

**Comment by qurben** [comment]
We zouden wel bij die paar duplicaten gewoon een error kunnen gooien bij reset met: 'he stuur de pubcie een mail'
