### ISSUE TITLE
CAPTCHA op interesseformulier

### ISSUE THREAD

**Issue by FrostMegaByte** [csrdelft/csrdelft.nl#606]
Het interesseforumulier ontvangt zeer veel spam. Om dit tegen te gaan zou er onderaan het formulier eigenlijk een CAPTCHA moeten komen, zodat bots niet kunnen blijven spammen.

**Comment by mathcals** [comment]
In df199b7 is ReCaptcha verwijderd zo te zien

**Comment by qurben** [comment]
Kunnen we niet iets beters verzinnen? Op het forum krijgen we nauwelijks spam binnen, terwijl daar ook geen captcha op zit.

**Comment by mathcals** [comment]
We kunnen ook een extra input toevoegen die we met CSS verbergen en dan checken of die leeg is. Ik weet niet of spambots daar in trappen.

**Comment by qurben** [comment]
Recaptcha is weer toegevoegd
