### ISSUE TITLE
Ga terug naar goede pagina na inloggen

### ISSUE THREAD

**Issue by qurben** [csrdelft/csrdelft.nl#62]
Ga naar de pagina waar de gebruiker vandaan kwam als een sessie verloopt en de gebruiker logt opnieuw in, bijvoorbeeld na opnieuw opstarten.

**Comment by brussee** [comment]
FYI: De filosofie van Android is dat als de gebruiker een tijdje niets heeft uitgevoerd in een app dat je dan een verse start (Task) wil maken.

Een sessie zou niet moeten verlopen als de gebruiker actief is (gebeurd nu wel en is een bug in mijn ogen) en zou de sessie key moeten vernieuwen zonder de gebruiker eruit te schoppen.

**Comment by qurben** [comment]
En wat als Jan Lid mij een link naar een draadje stuurt en ik ben niet ingelogd? Dan moet ik inloggen en daarna een aantal keer op terug klikken of de link nog een keer opzoeken.

**Comment by brussee** [comment]
Die feature zou al moeten werken: https://github.com/csrdelft/csrdelft.nl/blob/2a673f892ce80d40426dab7c2aa45e335c3cf844/lib/controller/LoginController.class.php#L85

**Comment by qurben** [comment]
Dan is dat stuk

**Comment by qurben** [comment]
`htdocs/index.php#L33` gooit roet in het eten

**Comment by brussee** [comment]
Aha.
'goback' vlak daarvoor setten?
