### ISSUE TITLE
API 2.0 security leak

### ISSUE THREAD

**Issue by brussee** [csrdelft/csrdelft.nl#63]
De controllers van de stek worden niet gebruikt en daardoor wordt het gehele interne rechtensysteem omzeild.

Tip: kijk naar hoe AclController en Controller werken, dat helpt je denk ik ook meer structuur aan te brengen in api.php

https://github.com/csrdelft/csrdelft.nl/blob/master/lib/controller/framework/AclController.abstract.php
https://github.com/csrdelft/csrdelft.nl/blob/master/lib/controller/framework/Controller.abstract.php

**Comment by brussee** [comment]
@Manduro

**Comment by brussee** [comment]
Hier is de lijst van permissies waar je op moet checken: https://github.com/csrdelft/csrdelft.nl/blob/master/lib/model/security/AccessModel.class.php#L282

**Comment by Manduro** [comment]
Het is echt niet zo dat het gehele rechtensysteem wordt omzeild, die checks zitten ook in de functies die ik heb gebruikt. 

Het kan natuurlijk op een mooiere manier, maar dat is mij niet gelukt als php leek zonder documentatie.

**Comment by brussee** [comment]
In de MVC structuur van de stek checkt de controller de toegang van de gebruiker tot de actie op een object of set van objecten.
Er zijn inderdaad functies in het model bij sommige objecten die rechten checken, maar die worden dus in principe aangeroepen vanuit de controller (ja soms doet de view het en dat is niet de bedoeling), het model doet dat vanwege performance redenen niet zelf. (1x de actie checken is genoeg, niet intern nog elke property access checken oid)

Het rechten systeem is het best gedocumenteerde deel van de stek met standaard terminologie. Laat me weten wat je daar niet aan snapt, dan kan ik het verbeteren. Ik heb beveiliging graag hoog in het vaandel staan met zoveel persoonsgegevens.

**Comment by Manduro** [comment]
Prima, ik snap het idee. Maar ik kwam er zo snel niet uit en heb van alles gecheckt of toegang gecontroleerd werd, dus je titel is nogal overdreven. Het is zeker geen perfecte implementatie en verbeteringen (en toevoegingen) zijn natuurlijk helemaal welkom.

**Comment by brussee** [comment]
Misschien heb ik niet goed genoeg gekeken, maar op welk punt in de code van de api wordt P_LEDEN_READ en P_OUDLEDEN_READ gecheckt dan?

**Comment by Manduro** [comment]
Je moet ingelogd zijn voordat je de api kan gebruiken. Verder wordt je uid opgeslagen in het authenticatie token. Deze wordt bijvoorbeeld gebruikt om te kijken of je je wel mag aanmelden voor een maaltijd. Het wordt bijna niet in de api code zelf gedaan, maar wel in de functies die de api aanroept.

**Comment by brussee** [comment]
Mooi, dan is met #67 de boel weer helemaal in orde.
