### ISSUE TITLE
Te veel maaltijden in archief

### ISSUE THREAD

**Issue by qurben** [csrdelft/csrdelft.nl#64]
Er staan te veel maaltijden in het [archief](https://csrdelft.nl/maaltijdenbeheer/archief), hierdoor gaat smarty over z'n nek met een mooie 500 error.

```
message: Allowed memory size of 134217728 bytes exhausted (tried to allocate 10125312 bytes)
file: beheer_maaltijd_archief.tpl.php
line: 53
request_url: /maaltijdenbeheer/archief
```

**Comment by brussee** [comment]
In het forum wordt paging gebruikt. Dat kun je eventueel overnemen.

Een andere optie is refactoren naar DataTable en de json door de client laten parsen.
