### ISSUE TITLE
Ledenmemory pasfoto's verhouding

### ISSUE THREAD

**Issue by brussee** [csrdelft/csrdelft.nl#651]
De pasfoto's zijn niet meer vierkant waardoor de hoogte-breedte-verhouding niet meer klopt.

**Comment by jptned** [comment]
De functie van de ledenmemory is voor het grootste deel overgenomen door [namen leren](https://www.csrdelft.nl/leden/namen-leren). Ik vraag me af in hoeverre we dit überhaupt nog in de stek hoeven te laten.

**Comment by mathcals** [comment]
Op zich wel leuk om ledenmemory te houden toch. Deze bug os ook makkelijk te fixen.
