### ISSUE TITLE
Contactformulier verplaatsen en verbouwen externe stek

### ISSUE THREAD

**Issue by Jobkanis** [csrdelft/csrdelft.nl#671]
Zoals op pagina 20 en 21 van dit document beschreven staat: [Webstek indeling PromoCie 2019.pdf](https://github.com/csrdelft/csrdelft.nl/files/4553055/Webstek.indeling.PromoCie.2019.pdf)

Kort samengevat: Het contact forumulier moet worden aangepast en zonder contactbalk verplaatst naar de pagina 'Lid Worden'.

**Comment by jptned** [comment]
Los interesseformulier geplaatst op lid worden pagina
