### ISSUE TITLE
CMS pagina's vullen met nieuwe tekst en plaatjes op de externe stek

### ISSUE THREAD

**Issue by Jobkanis** [csrdelft/csrdelft.nl#673]
De pagina's en de plaatjes van de externe stek moeten worden vervangen. De nieuwe tekst en plaatjes staan beschreven in dit bestand:  [Webstek indeling PromoCie 2019.pdf](https://github.com/csrdelft/csrdelft.nl/files/4553055/Webstek.indeling.PromoCie.2019.pdf)

Helaas werken de linkjes naar de gewenste plaatjes in dit bestand niet meer. Deze heb ik nu grotendeels op mijn computer staan. Laat maar even weten als je ze nodig hebt!

**Comment by qurben** [comment]
Wordt dit niet al gefixt door @FrostMegaByte ?

**Comment by FrostMegaByte** [comment]
Ja, klopt. Ik ben dit aan het fixen en is echt al bijna klaar

**Comment by Rickkert00** [comment]
In hoeverre moeten de dingen in CMS nog worden aangepast? Gaat het nu vooral over de teksten op de bestaande paginas, of moeten er ook nog nieuwe paginas/fotoslides worden toegevoegd zoals in het document staan? (Owee pagina)

**Comment by Rickkert00** [comment]
De paginas `vereniging/xxxxx` zijn nu aangepast behalve `vereniging/algemeen`
