### ISSUE TITLE
Menu externe stek verbeteren

### ISSUE THREAD

**Issue by Jobkanis** [csrdelft/csrdelft.nl#674]
Het menu en het bijhorende doorstroomschema tussen de pagina's van de externe stek staat op pagina 3 van dit bestand beschreven:  [Webstek indeling PromoCie 2019.pdf](https://github.com/csrdelft/csrdelft.nl/files/4553055/Webstek.indeling.PromoCie.2019.pdf)

**Comment by qurben** [comment]
Zie ook #666, #668 en #667

**Comment by qurben** [comment]
Gefixt in #668
