### ISSUE TITLE
Implementeren plaetjes over de volledige breedte van de externe stek

### ISSUE THREAD

**Issue by Jobkanis** [csrdelft/csrdelft.nl#675]
Op (volgens mij elke, maar in ieder geval op de hoofdpagina) pagina van de externe stek moet er een foto over de hele breedte worden getrokken. Dit is te zien op het voorbeeld van pagina 6 en 17 van het volgende bestandje:  [Webstek indeling PromoCie 2019.pdf](https://github.com/csrdelft/csrdelft.nl/files/4553055/Webstek.indeling.PromoCie.2019.pdf)

**Comment by qurben** [comment]
Ik kom er net achter dat ik dit al een keertje heb gebouwd, met de volgende html kan een volledige breedte afbeelding geplaatst worden.

```html
<section class="wrapper-img">
  <img src="/fotoalbum/Publiek/Voorpagina/CSR_Delft-min.jpg" alt="Foto vereniging"/>
</section>
```

Waar wel rekening mee gehouden moet worden dat de plaetjes die hier voor gebruikt worden goed geminimized zijn, want het is peperduur om grote plaetjes te laden.

Lazyload kan hier ook goed voor worden gebruikt.
