### ISSUE TITLE
Inschrijfformulier extern beschikbaar maken

### ISSUE THREAD

**Issue by jptned** [csrdelft/csrdelft.nl#690]
@jptned Heeft een lijstje met ideeën / velden gekregen die via de externe stek (o.b.v. een link) ingevuld moeten worden

**Comment by jptned** [comment]
@qurben Ik begrijp net van de OWee'cie dat inschrijven voor de OWee nog niet is toegestaan, dus dit heeft nog geen haast

**Comment by qurben** [comment]
Gefixt in #725
