### ISSUE TITLE
Onderzoeken welke sanitizing goed is voor e-mailnamen

### ISSUE THREAD

**Issue by jptned** [csrdelft/csrdelft.nl#711]
`FILTER_SANITIZE_EMAIL` is té scherp voor e-mailnamen: het filtert ook de spaties eruit:
![image](https://user-images.githubusercontent.com/8656358/85957052-4ad01e00-b98a-11ea-9679-1445c1f67c9d.png)

Er moet dus een alternatief gevonden worden wat passend is om spamfilter te vermijden maar wél de juiste naam mee te sturen (wat ook goed voor spamfilters is).

https://github.com/csrdelft/csrdelft.nl/blob/d1ba24ba1e122281728265a7d17a897a1d3cf996/lib/common/Mail.php#L53
https://github.com/csrdelft/csrdelft.nl/blob/d1ba24ba1e122281728265a7d17a897a1d3cf996/lib/common/Mail.php#L70
https://github.com/csrdelft/csrdelft.nl/blob/d1ba24ba1e122281728265a7d17a897a1d3cf996/lib/common/Mail.php#L91
https://github.com/csrdelft/csrdelft.nl/blob/d1ba24ba1e122281728265a7d17a897a1d3cf996/lib/common/Mail.php#L113

**Comment by qurben** [comment]
Oh `FILTER_SANITIZE_EMAIL` zou volgens mij ook alleen voor emailadressen gebruikt moeten worden en dus niet voor de naam.

**Comment by qurben** [comment]
> The FILTER_SANITIZE_EMAIL filter removes all illegal characters from an email address.

**Comment by qurben** [comment]
Ik zou zeggen dat `FILTER_SANITIZE_STRING` hier voldoet.
