### ISSUE TITLE
Opdateren inhoud externe stek

### ISSUE THREAD

**Issue by Jobkanis** [csrdelft/csrdelft.nl#716]
Aanpassingen hoofdpagina 

- op de hoofdpagina staat dat we zo’n 270 leden hebben, geloof dat dat nu rond de 220 is toch?
- onder het filmpje ‘studie is maar de helft’ staat nog: ‘vul het interesseformulier onderaan deze pagina in’, die hebben we dus weggehaald. Dus je kan beter verwijzen naar de OWee website
- C.S.R. in de OWee: staat dat we open zijn van 17-20 augustus, das nie waar. Dus even die laatste zin veranderen in ‘Ook C.S.R. doet mee aan deze gezellig week. Van 14 t/m 16 augustus zijn wij online te zien en van 17 t/m 22 augustus heb je de gelegenheid om fysiek de sfeer van C.S.R. en Delft te proeven!’ (zoiets)
- Interesse/vragen: Ten eerste even die ‘Vul het interesseformuler in’ misschien veranderen in ‘Laat je interesse weten’ en dan doorklikken naar de Lidspreken/inschrijven/Maartje appen op de OWee pagina 
- De tekst die daar staat verander dat maar naar: ‘Uiteraard is er de mogelijkheid om ons tijdens de OWee te spreken. Er is daarnaast ook gelegenheid om onze sociëteit Confide aan de Oude Delft 9 te bezoeken. Buiten de OWee om kan jij ook gewoon al jouw vragen aan ons stellen. Ben jij bijvoorbeeld geinteresseerd om een C.S.R. activiteit bij te wonen of een C.S.R. huis te bezoeken? Laat dat dan aan ons weten en kom erachter wat er allemaal mogelijk is.’
- die tekst eronder met ‘wil je lid worden.....’ -> ‘Wil je lid worden? Inschrijven kan in de OWee (17 t/m 22 augustus). Voorinschrijven is zelfs ook al mogelijk, zodat er tijdens de OWee meteen contact met je kan worden opgenomen. Doe dit door hier te klikken. Zorg ervoor dat je de week van 24 t/m 30 augustus vrij houdt voor de novitiaatsweek.’

Aanpassingen vereniging sub-pagina
- Onder ‘Vereniging van christenstudenten’ staat nog 58 jarig bestaan, is 59 geloof ik (dat staat iig op de hoofdpagina)
- Ook aantal leden hier is 260 -> 220 (?)

Aanpassingen vereniging -> gezelligheid: maaltijden
- ipv ‘Mocht je geinteresseerd zijn...’ -> ‘Op dit moment zijn er in verband met corona-maatregelen geen maaltijden te bezoeken, zodra dat weer kan laten we het weten!’

**Comment by Rickkert00** [comment]
Deze puntjes zijn allemaal gefixt!
