### ISSUE TITLE
Nieuwe externe layout

### ISSUE THREAD

**Issue by qurben** [csrdelft/csrdelft.nl#75]
De layout van de owee bevalt me wel, dus als we deze kunnen omzetten naar de normale C.S.R. kleuren zou dat wel mooi zijn.

**Comment by brussee** [comment]
Zijn de normale C.S.R. kleuren niet ook donkerblauw en geel? (Naast het zwart-wit logo?) https://csrdelft.nl/wiki/cie:huisstijl
Het is in ieder geval _altijd zo geweest_: https://trac.knorrie.org/csrdelft.nl/attachment/ticket/136/actueel_overzicht.png

**Comment by qurben** [comment]
Ik vind zoals de kleuren nu zijn een beetje heftig, ik ben zelf meer fan van het rustige wit/grijs met blauw wat het default interne thema heeft.

**Comment by brussee** [comment]
Ben het helemaal met je eens @qurben 

Hebben de mensen die vorig jaar met de huisstijl van C.S.R. bezig zijn geweest nog input voor dit onderwerp geleverd?

**Comment by thervh70** [comment]
PubCie heeft niet de vormgevingsskills in huis om dit goed te krijgen. In de aanloop naar komende OWee zal de voorpagina wel opnieuw gestyled worden.
