### ISSUE TITLE
Forum ongelezen wordt niet goed geupdate

### ISSUE THREAD

**Issue by qurben** [csrdelft/csrdelft.nl#759]
Bij het lezen van een forumdraadje wordt niet alles goed geupdate, hierdoor blijft een draadje soms op ongelezen staan.

**Comment by jptned** [comment]
Is dit niet een caching probleem? Als je een draadje leest, teruggaat en dan refresht wordt hij namelijk wel gelezen.

Zou alleen niet helemaal verklaren waarom het niet als gelezen in de zijbalk komt als je op het draadje zelf zit

**Comment by qurben** [comment]
Ja het lijkt inderdaad een caching issue, maar ik heb nog niet kunnen ontdekken waar het precies mis gaat. 

Het lijkt dat deze waardes op twee verschillende plekken gecached wordt en dat er maar eentje geupdate wordt bij het markeren als ongelezen.

**Comment by jptned** [comment]
Is het niet Http caching? Volgens mij gaat het alleen fout als je een pagina teruggaat

**Comment by qurben** [comment]
Zou zeggen dat `Cache-Control: max-age=0, must-revalidate, private` en een `Expires` in het verleden er wel voor zou moeten zorgen dat dit niet gecached wordt.

**Comment by qurben** [comment]
Als ik op mijn lokale stek een bericht maak en daarna ververs met ctrl+f5 staat het lijntje nog steeds boven mijn nieuwe bericht.

**Comment by qurben** [comment]
Waarschijnlijk zorgt `ForumDraad::getWanneerGelezen` voor problemen

https://github.com/csrdelft/csrdelft.nl/blob/fe1bf4ec7ed3025ff231196d62ef8297f956ad82/lib/entity/forum/ForumDraad.php#L249

**Comment by qurben** [comment]
Flushen van de memcache zet ongelezen weer goed.

**Comment by qurben** [comment]
Gefixt in 47edf831294746eca81cdda6cb99ba5617ebb0e4
