### ISSUE TITLE
Versiering lichting 20 

### ISSUE THREAD

**Issue by Rickkert00** [csrdelft/csrdelft.nl#775]
Een aantal ideeën: 

- Romeinen die langslopen
- Speren die door het scherm gaan
- Druiven die uit profielfotos vallen
- Helm op profielfoto

**Comment by Jobkanis** [comment]
Zullen we dan voor de druiven die uit de profielfoto's vallen gaan? Tim zei dat daarvoor misschien matter.js gebruikt kan worden.

**Comment by jptned** [comment]
Was niet ik die dat zei 🙊
Ik denk dat Matter.js op de stek een beetje te intensief is voor een effectje als dit

**Comment by qurben** [comment]
Matter.js is denk ik ook een beetje overkill hier voor, physics is grappig, maar niemand die ziet of de physics een beetje echt zijn.

**Comment by jptned** [comment]
Mijn voorstel zou zijn: profielfoto's van 20'jes een `::after` geven met een druif en die bij scroll laten animeren (css transition ease-in) van de positie van de profielfoto naar onderaan buiten het scherm

**Comment by Rickkert00** [comment]
Ik zal het proberen zonder matter.js te doen, bedankt voor de tip Tim
