### ISSUE TITLE
Foutmelding bij bewerking van lidprofiel, maar bewerking lukt wel.

### ISSUE THREAD

**Issue by jeanine1997** [csrdelft/csrdelft.nl#776]
"Opslaan van 5 wijziging(en) mislukt"

Bij iets bewerken van een profiel van een willekeurig lid, wordt er standaard een dergelijke foutmelding gegeven, terwijl het wel goedgaat

**Comment by qurben** [comment]
https://github.com/csrdelft/csrdelft.nl/blob/master/lib/controller/ProfielController.php#L278-L280
