### ISSUE TITLE
Noviet van de dag veld

### ISSUE THREAD

**Issue by Jobkanis** [csrdelft/csrdelft.nl#787]
Graag:
* Op een zichtbare plek
* Willekeurige lijst aan novieten met een foto, naam, studie en geboortejaar
* Elke dag een nieuwe noviet
* Nadat elke noviet is geweest, wordt er weer een nieuwe lijst gegenereerd.

**Comment by Jobkanis** [comment]
Als ik Am. Nederveen mag citeren: ' Handigst is dan waarschijnlijk om een seed te gebruiken om een permutatie te maken van novieten en dan op basis van de datum de huidige noviet van de dag te kiezen.'

**Comment by jptned** [comment]
Gefixt in #789
