### ISSUE TITLE
Alternatief ketzer systeem voor Studeer ketzers en Borrel ketzers 

### ISSUE THREAD

**Issue by Jobkanis** [csrdelft/csrdelft.nl#788]
### Taken
Deelnemer
- [ ] Lijst activiteiten bekijken (@Jobkanis)
- [ ] BB tag voor activiteitinfo
- [ ] BB tag voor komende activiteiten
- [ ] Eigen historie bekijken
- [ ] Aanmelden (@jptned)
- [ ] Afmelden (@jptned)
	
Beheerder
- [ ] Reeks CRUD
- [ ] Activiteit CRUD

Deelnemerlijst
- [ ] Lijst zien
- [ ] Mensen toevoegen
- [ ] Mensen verwijderen
- [ ] Gasten aanpassen
- [ ] Aanmeldingen sluiten

### Beschrijving
Op aanvraag van het bestuur: een nieuw inketzsysteem voor herhalende activiteiten. Dit zal onder anderen gebruikt worden voor studeerplek ketzers en borrelketzers.

**Moet hebben:**
- Simple layout vergelijkbaar met maaltijd ketzers.
	- Zichtbaar op de hoofdpagina
	- Bevat een titel
	- Bevat een plek voor een beschrijving. Dit zou bijvoorbeeld gebruikt kunnen worden voor teksten zoals: 'Bij aanmelden gaat u akkoord met de volgende voorwaarden _link_.'
	- Bevat de begin en einddatum van de activiteit (dit kan eventueel worden gecombineerd met het titel- of beschrijvingsveld)
	- Bevat een knop waarbij een lid op kan klikken om zich in of uit te ketzen
- Een mogelijkheid om deze ketzer automatisch aan te laten maken.
	- Heeft een startdatum waarop de ketzer opent en leden zich in kunnen ketzen
	- Heeft een einddatum waarop de ketzer sluit en leden zich niet meer kunnen ketzen
	- Heeft een begin en einddatum voor de activiteit.
	- Een maximaal toegestane hoeveelheid leden.
	- Een mogelijkheid om de instellingen voor een activiteit te herhalen (voor bijvoorbeeld wekelijkse activiteiten). Misschien kan dit worden gedaan door data te selecteren in een kalender.
- Een mogelijkheid voor mensen met de juiste rechten (bestuur/soccie, etc.) om een lijst met aanwezigen te zien
	- Optimaal zou dit te exporteren moeten zijn naar PDF en/of Excel.
- Mogelijkheid tot het aanpassen van bestaande ketzers.

**Kan hebben**
- Een mogelijkheid tot het invullen van een aantal vragen. Dit kunnen meerkeuze of open vragen zijn. Idealiter opent een pop-up zich waarop het lid een aantal vragen in kan vullen. Na het invullen van deze vragen kan er op een knop _inketzen_ worden geklikt, waarna het lid officieel ingeketzt staat. Dit zal bijvoorbeeld gebruikt kunnen worden voor de corona gezondheidsvragen.
- Eventueel hetzelfde systeem ook bruikbaar maken op het forum. 

**Doodlijntjes:**
- **7 januari:** een foto/screenshot van het ontwerp van het inketzsysteem. Dit hoeft alleen een algemene indruk te zijn van het systeem dat in het protocol naar de gemeente kan worden gestuurd.
- **19 januari**: Werkende versie inketzssysteem. Vanaf dan kan er hopelijk fysiek gestudeerd worden op Confide.

**Comment by Jobkanis** [comment]
Na gebeld te hebben met het bestuur, heb ik de beschrijving aangepast!

**Comment by jptned** [comment]
Misschien handig bij ontwerpen rekening mee te houden:

**Zal wel/niet hebben:**

- Mogelijkheid tot wachtlijsten & borrelpunten

**Comment by brussee** [comment]
Je kunt naar MaaltijdRepetitie kijken ter inspiratie. Ook abonnementen zijn daarbij geïmplementeerd.
Als je een wachtlijst/automatische reserveketzer-systeem implementeerd zou het maaltijdsysteem daar ook profijt van hebben.
