### ISSUE TITLE
Pinmatchtool haalt geen transacties meer op uit PayPlaza

### ISSUE THREAD

**Issue by jptned** [csrdelft/csrdelft.nl#800]
Bij importeren komen transacties van het pinapparaat niet door

**Comment by qurben** [comment]
Lijkt erop dat hun stek is veranderd

**Comment by jptned** [comment]
Was ik al bang voor, zat er natuurlijk een keer aan te komen 😅

**Comment by jptned** [comment]
Probleem zit niet in verandering in Payplaza maar in problemen met SSL. Zowel lokaal als op de server faalt cURL met de foutmelding `SSL certificate problem: unable to get local issuer certificate`. Lokaal al geprobeerd met een verse certfile, maar dat werkt ook niet...

**Comment by qurben** [comment]
De certificate zelf laden ergens?

**Comment by jptned** [comment]
Wij kunnen zelf niet bij de configuratie daarvan op de server, toch? Een custom certificaat gebruiken bij de cURL requests zou kunnen vanuit PHP, maar dan gaat het stuk op het moment dat Payplaza z'n certificaat ververst

**Comment by jptned** [comment]
Probleem lijkt te zitten in dat Payplaza een incomplete chain geconfigureerd heeft: https://www.ssllabs.com/ssltest/analyze.html?d=portal.payplaza.com&hideResults=on

> At times, you find that the verification works in your favorite browser but fails in curl. When this happens, the reason is usually that the server sends an incomplete cert chain. The server is mandated to send all "intermediate certificates" but doesn't. This typically works with browsers anyway since they A) cache such certs and B) supports AIA which downloads such missing certificates on demand. This is a server misconfiguration.

Zal sowieso even een berichtje achterlaten bij Payplaza, maar moeten dus even een manier vinden om dit in de tussentijd op te lossen. SSL uitzetten op deze requests zou kunnen, maar weet niet of dat heel verantwoord is 😅

**Comment by jptned** [comment]
Tijdelijk opgelost met een mogelijkheid handmatig te downloaden zonder SSL validate (c5a90e14876751476b6cbae39c78fb560dabbf75)
Het is wachten op Payplaza voor een permanente oplossing

**Comment by jptned** [comment]
Payplaza gaat het voorlopig niet fixen, dus permanent uitgezet in 28f47f41
