### ISSUE TITLE
Verjaardagen worden niet gesynchroniseerd met iCal

### ISSUE THREAD

**Issue by jptned** [csrdelft/csrdelft.nl#804]

**Comment by jptned** [comment]
De verjaardagen in de iCal hebben een datum in 2022

**Comment by qurben** [comment]
Gerelateerd aan #613 #182? 😛

**Comment by jptned** [comment]
Zat ik ook al naar te kijken, maar het gaat ook bij andere maanden fout

**Comment by jptned** [comment]
Het gaat fout omdat `$van` (1 maand geleden) nog in 2020 ligt en `$tot` (over 12 maanden) al in 2022. Hij pakt dan de 2022-versie. Ik ga 'm fixen
https://github.com/csrdelft/csrdelft.nl/blob/9d2cf8b02b294f83c4bf5300ebfa74a0130bf41d/lib/entity/profiel/Profiel.php#L562-L566
