### ISSUE TITLE
Donker thema verbeteringen

### ISSUE THREAD

**Issue by qurben** [csrdelft/csrdelft.nl#810]

**Comment by qurben** [comment]
> [▶](https://csrdelft.nl/forum/reactie/127990#127990) in het donkere thema (dat op zich heel fijn is) zijn sommige lettertype niet te lezen. Bijvoorbeeld de huidige paginanummer onderaan het draadje (wat geselecteerd is in plaetje). Mss kan het contrast omhoog? 

>  [▶](https://csrdelft.nl/forum/reactie/127997#127997) Om de vorige reactie aan te vullen: de forumlijst met alle titels is ook erg slecht te lezen door het gebrek aan contrast tussen de blauwe letters en de donkere achtergrond.

**Comment by FrostMegaByte** [comment]
De 2 benoemde problemen zijn gefixt
