### ISSUE TITLE
Composite keys Yes/No?

### ISSUE THREAD

**Issue by brussee** [csrdelft/csrdelft.nl#82]
From https://github.com/csrdelft/csrdelft.nl/pull/41#discussion_r77458555
> Omdat EntityField een relatie aangeeft tussen de entity van het formulier en de entity van het EntityField. Als de entity uit het EntityField een composite primary key heeft, moet de entity van Formulier een composite foreign key hebben, dit werkt nog niet in Formulier.

Exact :-) Dit is precies waarom EntityField niet is afgemaakt door mij, want het framework heeft nog geen ondersteuning voor foreign keys, laat staan composite foreign keys. Ik zit nu dus af te wegen of we gewoon geen composite keys meer willen (gebruikelijk en mijn voorkeur) of UUID telkens encoden/decoden.

FK support is erg eenvoudig toe te voegen, het is dus vooral de design keuze op het punt van composite keys. Wat vind jij @qurben ?

**Comment by brussee** [comment]
Alles wordt simpeler zonder samengestelde keys en je verliest geen functionaliteit, dus ik denk eigenlijk dat de keuze eenvoudig is. Mee eens?

From https://dev.mysql.com/doc/refman/5.5/en/optimizing-primary-keys.html
> 8.3.2 Using Primary Keys
> 
> The primary key for a table represents the column or set of columns that you use in your most vital queries. It has an associated index, for fast query performance. Query performance benefits from the NOT NULL optimization, because it cannot include any NULL values. With the InnoDB storage engine, the table data is physically organized to do ultra-fast lookups and sorts based on the primary key column or columns.
> 
> If your table is big and important, but does not have an obvious column or set of columns to use as a primary key, you might create a separate column with auto-increment values to use as the primary key. These unique IDs can serve as pointers to corresponding rows in other tables when you join tables using foreign keys.

**Comment by brussee** [comment]
More relevant info: https://dev.mysql.com/doc/refman/5.5/en/multiple-column-indexes.html

**Comment by qurben** [comment]
In #41 heeft EetplanBekenden een composite key (de hele tabel). Ik weet niet of er nog andere entities zijn die een composite key hebben.

Mijn voorkeur gaat ook uit naar simpele keys. Er zijn weinig cases waar composite keys echt iets toevoegen, en op deze plekken is een simpele key ook gewoon mogelijk. Daarnaast versimpelt dit het framework ook een stuk.

**Comment by brussee** [comment]
Er zijn meerdere koppeltabellen (bijv. PK: draad_id, uid) die ook niet met een simpele EntityField af kunnen. Dat moet een tabelletje worden met + - buttons.

#83 regelt in ieder geval de basis id met optioneel je nog steeds composite PK. Je kunt in plaats van EntityField ook gewoon een IntField gebruiken zoals bij maalcie/Taakform maaltijd_id.

**Comment by brussee** [comment]
> FK support is erg eenvoudig toe te voegen

Dit valt erg tegen, want de restricties worden in een aparte schema opgeslagen in mysql dus automatisch aanmaken en verwijderen is niet triviaal.

**Comment by brussee** [comment]
Ik laat het zoals het is, want UUID telkens encoden/decoden is geen ramp, zie voorbeeld: https://github.com/brussee/csrdelft.nl/blob/522e0f6579db3f1326a8eac6c14e988519e9f9d8/lib/model/framework/PersistenceModel.abstract.php#L242
