### ISSUE TITLE
Bug meescrollende zijbalk

### ISSUE THREAD

**Issue by qurben** [csrdelft/csrdelft.nl#843]
Met een specifieke hoogte van een pagina + zijbalk gaat get scherm 'trillen'. Zie bijgevoegde video, gebeurt in Chrome.

https://user-images.githubusercontent.com/589651/111156527-21960300-8596-11eb-8269-956e5388a101.mp4

Lijkt te komen door de nieuwe meescrollende zijbalk.

**Comment by jptned** [comment]
Ik was al bezig met wat verbeterde logica hiervoor
