### ISSUE TITLE
 'Uit de ketzer halen' haalt jezelf uit de ketzer

### ISSUE THREAD

**Issue by jptned** [csrdelft/csrdelft.nl#844]
Reproduceren:

1. Ketz je in in een ketzer
2. Klik met rechtermuisklik op een andere persoon in de ketzer
3. Klik op 'Uit de ketzer halen'

I.p.v. de persoon die je selecteert, word je zelf uit de ketzer gehaald.

**Comment by qurben** [comment]
Schopje, was net een lid die zichzelf ongewild had verwijderd.
