### ISSUE TITLE
Refactor Courant

### ISSUE THREAD

**Issue by qurben** [csrdelft/csrdelft.nl#9]

**Comment by qurben** [comment]
Afwachten van uitkomsten CommunicaCie

**Comment by mathcals** [comment]
Zit nog een hoop MySqli in die herschreven kan worden.

**Comment by FrostMegaByte** [comment]
Job Bakker en Julian Aantjes gaan dit op zich nemen om de courant remake te verwezenlijken

**Comment by qurben** [comment]
Er moeten ook wat backend dingen gerefactored worden hiero. Het lijkt me goed dat als Bakker en Aantjes een duidelijk idee hebben van hoe het eruit gaat zien dat de backend ook omgebeund wordt om eventueel nieuwe ideeen te ondersteunen.

**Comment by qurben** [comment]
Done in #566
