### ISSUE TITLE
Ketzer verwijderen geeft 500

### ISSUE THREAD

**Issue by jptned** [csrdelft/csrdelft.nl#901]
![image](https://user-images.githubusercontent.com/8656358/123408795-b6ed5e00-d5ad-11eb-9c3f-32bf1ac60832.png)

Gegeven foutmelding:
```Call to a member function getLink() on null```

**Comment by jeanine1997** [comment]
Ketzer aanmaken heeft ook kuren 
![image](https://user-images.githubusercontent.com/55959048/123771065-0e9c0a00-d8cb-11eb-8f60-705e66081136.png)
