### ISSUE TITLE
Forum C.S.R.-zaken verwijzing is kapoet

### ISSUE THREAD

**Issue by jeanine1997** [csrdelft/csrdelft.nl#909]
Op deze manier naar forum C.S.R.-zaken gaan
![image](https://user-images.githubusercontent.com/55959048/125446372-caa84dc0-8bb4-4e90-bf07-0e2b0435f564.png)

Geeft deze pagina
![image](https://user-images.githubusercontent.com/55959048/125446326-a7207bd5-a618-46f7-a6b4-ec193b04a185.png)

Sip

**Comment by qurben** [comment]
Fout in bb to prosemirror van het huidige concept

**Comment by qurben** [comment]
Gefixt in 332463236
