### ISSUE TITLE
Clippy werkt niet meer

### ISSUE THREAD

**Issue by jptned** [csrdelft/csrdelft.nl#915]
CDN lijkt niet goed meer te werken: hij blijft oneindig laden

**Comment by jptned** [comment]
Ik heb 'm voor nu in ieder geval bij iedereen uitgezet

**Comment by JobdeVogel** [comment]
Pull request staat klaar

**Comment by Jobkanis** [comment]
https://github.com/csrdelft/csrdelft.nl/pull/982
