### ISSUE TITLE
Forumbericht concept blijft plakken na inzenden

### ISSUE THREAD

**Issue by qurben** [csrdelft/csrdelft.nl#93]

**Comment by brussee** [comment]
Doordat AbstractForumModel een CachedPersistenceModel is, is ForumReagerenModel dat ook en gaat het volgende mis:
```
$reageren = $this->getReagerenDoorLid($deel, $draad_id);
		if (empty($concept)) {
			if ($reageren) {
				$this->delete($reageren);
			}
...
```
De controlelr setConcept, maar update de cache niet (goed/bug?) en daardoor is bij de 2e keer setConcept $reageren nog steeds null en wordt het concept niet verwijderd. (denk ik)
