### ISSUE TITLE
Waarschuwing email vergeten externen forum komt in loginscherm

### ISSUE THREAD

**Issue by qurben** [csrdelft/csrdelft.nl#96]
De waarschuwing 'U moet een geldig emailadres opgeven' en 'SPAM' komen in het loginvenster terecht, omdat deze de eerste is die `getMelding` aanroept.

Hier moet iets slims op verzonnen worden.

**Comment by brussee** [comment]
> Hier moet iets slims op verzonnen worden.

Aparte $_SESSION keys gebruiken voor login meldingen en overige meldingen.

**Comment by brussee** [comment]
>> Hier moet iets slims op verzonnen worden.

> Aparte $_SESSION keys gebruiken voor login meldingen en overige meldingen.

Dit is blijkbaar al gedaan in LoginModel:
```
	public function hasError() {
		return isset($_SESSION['auth_error']);
	}
```
De view moet dus gewoon geen getMelding meer roepen maar getLoginMelding() en dan die error fetchen.

**Comment by brussee** [comment]
> De view moet dus gewoon geen getMelding meer roepen maar getLoginMelding() en dan die error fetchen.

En ook dat is dus al goed gedaan in LoginForm:
```
$fields[] = new HtmlComment('<p class="error">' . LoginModel::instance()->getError() . '</p>');
```

Wie roeps er dan getMelding() op de verkeerde plek?

**Comment by brussee** [comment]
Het probleem is inderdaad dat getMelding in view() door Formulier wordt geroepen en LoginForm extends Formulier:
```
	public function view() {
		parent::view();
		...
```
```
	/**
	 * Toont het formulier en javascript van alle fields.
	 */
	public function view() {
		echo getMelding();
		...
```

**Comment by brussee** [comment]
^ Opgelost
