### ISSUE TITLE
Markeer forumdraad als ongelezen bij openen draad

### ISSUE THREAD

**Issue by JobdeVogel** [csrdelft/csrdelft.nl#980]
Wanneer men op een draadje klikt in de menubalk wordt deze pas regular ipv italic nadat de pagina grefresht is. Zou logischer zijn als de font direct regular wordt wanneer je op het draadje geklikt hebt.

**Comment by qurben** [comment]
Als ik mij niet vergis is de fix hier om de gelezen datum te zetten naar een seconde (oid) in het verleden, zodat de templates duidelijk zien dat de draad gelezen is.
