### ISSUE TITLE
Verwijder Open avond form van externe stek

### ISSUE THREAD

**Issue by CodexNine** [csrdelft/csrdelft.nl#983]
- Open avond formulier weg
- Tekst aanpassen:
VAN:
We hebben twee keer dit jaar een open
avond waarbij je kan komen kijken hoe
een avond in onze sociëteit eruit ziet. Je
kan komen eten, meedoen met een
praise uur en komen borrelen. De
eerstvolgende open avond is donderdag
14 april 2022.

NAAR:
We hebben twee keer dit
jaar een open avond waarbij je kan komen kijken
hoe een avond in onze sociëteit eruit ziet. Je kan
komen eten, meedoen met een worshipavond en
komen borrelen. De eerstvolgende open
avond is op 2 juni, de inschrijvingen
daarvoor gaan 2 weken van tevoren
open.

**Comment by Jobkanis** [comment]
Moet het hele open avond formulier weg?
Of alleen het mee-eten gedeelte?

**Comment by Jobkanis** [comment]
![afbeelding](https://user-images.githubusercontent.com/22215251/166154353-41dd3022-a5ba-4475-a175-81864ebfb841.png)
