### ISSUE TITLE
Nieuw formulier open avond 2 juni

### ISSUE THREAD

**Issue by CodexNine** [csrdelft/csrdelft.nl#985]
Google docs formulier in externe stek (zoals de vorige)

**Comment by Jobkanis** [comment]
Deze snap ik niet helemaal. Welk formulier wordt er bedoelt en waar moet deze komen?

**Comment by Christof2000** [comment]
Hoe zag "de vorige" eruit?

**Comment by qurben** [comment]
7f55ac520145ca87ad9de51d1aaa71126d33b60f Deze commit (deels) reverten

**Comment by qurben** [comment]
Dit moet op 19 mei goed staan.
